Repository crabit-official/Crabit-FE2, pull requests merged in 2024-11, with the labels that each got.

#74 [CRAB-33] 대시보드 페이지 ui 수정
  public/images/logo_ncs.webp
  public/images/logo_nsc.webp
  public/images/test.jpeg
  src/app/academy/(workspace)/[id]/dashboard/@modal/(.)[contentId]/page.tsx
  src/app/academy/(workspace)/[id]/dashboard/@modal/default.tsx
  src/app/academy/(workspace)/[id]/dashboard/[challengeId]/page.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/ChallengeCard/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/MenuItem/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/Menubar/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/layout.tsx
  src/app/academy/(workspace)/[id]/dashboard/page.tsx
  src/app/academy/(workspace)/[id]/layout.tsx
  src/app/academy/(workspace)/[id]/market/@modal/(.)[...slug]/page.tsx
  src/app/academy/(workspace)/[id]/market/@modal/(.)[challengeId]/page.tsx
  src/app/academy/(workspace)/[id]/market/[...slug]/page.tsx
  src/app/academy/(workspace)/[id]/market/[challengeId]/page.tsx
  src/app/academy/(workspace)/[id]/market/components/ChallengeCardList/index.tsx
  src/app/academy/(workspace)/[id]/market/components/ChallengeTab/index.tsx
  src/app/academy/(workspace)/[id]/market/components/ModalDetail/index.tsx
  src/app/academy/(workspace)/[id]/market/page.tsx
  src/app/layout.tsx
  src/features/academy/(workspace)/components/workspace-tab.tsx
  src/features/main/components/MainBanner/index.tsx
  src/features/main/components/ThirdBanner/index.tsx
  src/shared/components/Framer/index.tsx
  src/shared/components/Logo/index.tsx
  src/shared/styles/globals.css
  tailwind.config.ts
Labels: ✨ feature

#75 [Deploy] 2024년 11월 6일 Daily Deploy
  public/images/logo_ncs.webp
  public/images/logo_nsc.webp
  public/images/test.jpeg
  src/app/academy/(workspace)/[id]/dashboard/@modal/(.)[contentId]/page.tsx
  src/app/academy/(workspace)/[id]/dashboard/@modal/default.tsx
  src/app/academy/(workspace)/[id]/dashboard/[challengeId]/page.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/ChallengeCard/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/MenuItem/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/Menubar/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/layout.tsx
  src/app/academy/(workspace)/[id]/dashboard/page.tsx
  src/app/academy/(workspace)/[id]/layout.tsx
  src/app/academy/(workspace)/[id]/market/@modal/(.)[...slug]/page.tsx
  src/app/academy/(workspace)/[id]/market/@modal/(.)[challengeId]/page.tsx
  src/app/academy/(workspace)/[id]/market/[...slug]/page.tsx
  src/app/academy/(workspace)/[id]/market/[challengeId]/page.tsx
  src/app/academy/(workspace)/[id]/market/components/ChallengeCardList/index.tsx
  src/app/academy/(workspace)/[id]/market/components/ChallengeTab/index.tsx
  src/app/academy/(workspace)/[id]/market/components/ModalDetail/index.tsx
  src/app/academy/(workspace)/[id]/market/page.tsx
  src/app/layout.tsx
  src/features/academy/(workspace)/components/workspace-tab.tsx
  src/features/main/components/MainBanner/index.tsx
  src/features/main/components/ThirdBanner/index.tsx
  src/shared/components/Framer/index.tsx
  src/shared/components/Logo/index.tsx
  src/shared/styles/globals.css
  tailwind.config.ts
Labels: 🍠 deploy

#77 [CRAB-34] 챌린지 상세 페이지 구현
  public/images/icons/icon_book.webp
  src/app/academy/(academy)/my/components/academy-list/index.tsx
  src/app/academy/(academy)/my/page.tsx
  src/app/academy/(workspace)/[id]/dashboard/[challengeId]/page.tsx
  src/app/academy/(workspace)/[id]/dashboard/[challengeId]/student/[studentId]/page.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/AllChallengeContents/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/ChallengeDetail/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/ChallengeStatistics/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/DonutChart/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/StudentCard/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/page.tsx
  src/features/academy/(workspace)/components/dashboard/best-challenge-table/index.tsx
  src/features/academy/(workspace)/components/state-label/index.tsx
  src/features/academy/(workspace)/components/workspace-tab.tsx
  src/features/main/components/LoginModal/index.tsx
  src/shared/apis/academy.ts
  src/shared/constants/student.ts
  src/shared/hooks/academy/useGetInfiniteAcademyList.ts
  tailwind.config.ts
Labels: ✨ feature

#78 [Deploy] 2024년 11월 7일 Daily Deploy
  public/images/icons/icon_book.webp
  src/app/academy/(academy)/my/components/academy-list/index.tsx
  src/app/academy/(academy)/my/page.tsx
  src/app/academy/(workspace)/[id]/dashboard/[challengeId]/page.tsx
  src/app/academy/(workspace)/[id]/dashboard/[challengeId]/student/[studentId]/page.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/AllChallengeContents/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/ChallengeDetail/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/ChallengeStatistics/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/DonutChart/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/StudentCard/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/page.tsx
  src/features/academy/(workspace)/components/dashboard/best-challenge-table/index.tsx
  src/features/academy/(workspace)/components/state-label/index.tsx
  src/features/academy/(workspace)/components/workspace-tab.tsx
  src/features/main/components/LoginModal/index.tsx
  src/shared/apis/academy.ts
  src/shared/constants/student.ts
  src/shared/hooks/academy/useGetInfiniteAcademyList.ts
  tailwind.config.ts
Labels: 🍠 deploy

#80 [CRAB-35] 로그인 쿠키 방식으로 변경
  src/app/academy/(academy)/my/components/academy-list/index.tsx
  src/app/academy/(academy)/my/page.tsx
  src/app/academy/(workspace)/[id]/setting/components/revoke-button/index.tsx
  src/app/api/academy/list/route.ts
  src/app/api/auth/login/route.ts
  src/app/api/auth/logout/route.ts
  src/app/api/auth/profile/route.ts
  src/features/main/components/LoginModal/index.tsx
  src/features/main/components/UserMenu/index.tsx
  src/features/space/enroll/components/form.tsx
  src/shared/apis/academy.ts
  src/shared/apis/challenge.ts
  src/shared/apis/fetch-data.ts
  src/shared/apis/set-auth-cookie.ts
  src/shared/constants/query-keys.ts
  src/shared/hooks/main/useGetProfile.ts
  src/shared/types/auth.ts
Labels: ✨ feature

#81 [Deploy] 2024년 11월 7일 Daily Deploy
  src/app/academy/(academy)/my/components/academy-list/index.tsx
  src/app/academy/(academy)/my/page.tsx
  src/app/academy/(workspace)/[id]/setting/components/revoke-button/index.tsx
  src/app/api/academy/list/route.ts
  src/app/api/auth/login/route.ts
  src/app/api/auth/logout/route.ts
  src/app/api/auth/profile/route.ts
  src/features/main/components/LoginModal/index.tsx
  src/features/main/components/UserMenu/index.tsx
  src/features/space/enroll/components/form.tsx
  src/shared/apis/academy.ts
  src/shared/apis/challenge.ts
  src/shared/apis/fetch-data.ts
  src/shared/apis/set-auth-cookie.ts
  src/shared/constants/query-keys.ts
  src/shared/hooks/main/useGetProfile.ts
  src/shared/types/auth.ts
Labels: 🍠 deploy

#84 [CRAB-37] 서버 에러를 받아오지 못하는 현상과, custom fetch hook 수정
  eslint/default.js
  src/app/api/academy/enroll/route.ts
  src/features/space/enroll/apis/use-enroll-academy.ts
  src/features/space/enroll/components/form.tsx
  src/shared/apis/fetch-data.ts
  src/shared/constants/api-error-message.ts
  src/shared/types/acadmy.ts
  yarn.lock
Labels: 🐛 bug

#89 [CRAB-39] Channel Talk 연결
  src/shared/components/ChannelTalk/index.tsx
  src/shared/components/QueryProvider/index.tsx
Labels: ✨ feature, 🌐 ci/cd

#91 [CRAB-38] 원장/강사 대시보드 및 챌린지 마켓 페이지 api 연결
  public/images/icons/icon_check.webp
  src/app/academy/(workspace)/[id]/dashboard/[challengeId]/page.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/AllChallengeContents/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/ChallengeDetail/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/ChallengeStatistics/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/MyChallengeContentForm/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/create/components/First.tsx
  src/app/academy/(workspace)/[id]/dashboard/create/components/Last.tsx
  src/app/academy/(workspace)/[id]/dashboard/create/components/MultiStepProgress/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/create/components/Second.tsx
  src/app/academy/(workspace)/[id]/dashboard/create/components/Third.tsx
  src/app/academy/(workspace)/[id]/dashboard/create/page.tsx
  src/app/academy/(workspace)/[id]/dashboard/page.tsx
  src/app/academy/(workspace)/[id]/market/@modal/(.)[challengeId]/page.tsx
  src/app/academy/(workspace)/[id]/market/[challengeId]/page.tsx
  src/app/academy/(workspace)/[id]/market/components/ChallengeCardList/index.tsx
  src/app/academy/(workspace)/[id]/market/components/ChallengeDetail/index.tsx
  src/app/academy/(workspace)/[id]/market/components/ModalDetail/index.tsx
  src/app/academy/(workspace)/[id]/market/page.tsx
  src/app/academy/(workspace)/[id]/members/detail/components/StudentDetailList/index.tsx
  src/app/academy/(workspace)/[id]/members/detail/page.tsx
  src/app/academy/(workspace)/[id]/members/instructor/components/InstructorDetailList/index.tsx
  src/app/academy/(workspace)/[id]/members/instructor/page.tsx
  src/app/academy/(workspace)/[id]/members/student/components/StudentDetailList/index.tsx
  src/app/academy/(workspace)/[id]/members/student/page.tsx
  src/app/academy/(workspace)/[id]/setting/page.tsx
  src/app/api/academy/students/route.ts
  src/app/api/challenge/create/route.ts
  src/app/api/challenge/delete/route.ts
  src/app/api/challenge/detail/route.ts
  src/app/api/challenge/student/approval/route.ts
  src/app/api/image/upload/route.ts
  src/app/api/market/release/route.ts
  src/features/academy/(workspace)/api/post-academy-challenges.ts
  src/features/academy/(workspace)/components/dashboard/ChallengeModal/First.tsx
  src/features/academy/(workspace)/components/dashboard/ChallengeModal/Second.tsx
  src/features/academy/(workspace)/components/dashboard/ChallengeModal/Third.tsx
  src/features/academy/(workspace)/components/dashboard/ChallengeModal/index.tsx
  src/features/academy/(workspace)/components/dashboard/Students/index.tsx
  src/features/academy/(workspace)/components/dashboard/academy-title/index.tsx
  src/features/academy/(workspace)/components/state-label/index.tsx
  src/features/academy/(workspace)/hooks/challenges/use-create-challenges.ts
  src/features/academy/(workspace)/utils/challengeState.ts
  src/shared/apis/academy.ts
  src/shared/apis/challenge.ts
  src/shared/apis/market.ts
  src/shared/constants/challenge-cataegrories.ts
  src/shared/enums/challenge.ts
  src/shared/hooks/academy/useGetInfiniteAcademyInstructorList.ts
  src/shared/hooks/academy/useGetInfiniteAcademyMemberDetailList.ts
  src/shared/hooks/academy/useGetInfiniteAcademyStudentList.ts
  src/shared/hooks/challenge/useDeleteChallenge.ts
  src/shared/hooks/images/use-get-presigned-url.ts
  src/shared/hooks/market/useReleaseChallenge.ts
  src/shared/hooks/use-step-progress.ts
  src/shared/types/acadmy.ts
  src/shared/types/images.ts
  src/shared/types/market.ts
  src/shared/utils/schema.ts
Labels: ✨ feature

#92 [Deploy] 2024년 11월 13일 Daily Deploy
  public/images/icons/icon_check.webp
  src/app/academy/(workspace)/[id]/dashboard/[challengeId]/page.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/AllChallengeContents/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/ChallengeDetail/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/ChallengeStatistics/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/MyChallengeContentForm/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/create/components/First.tsx
  src/app/academy/(workspace)/[id]/dashboard/create/components/Last.tsx
  src/app/academy/(workspace)/[id]/dashboard/create/components/MultiStepProgress/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/create/components/Second.tsx
  src/app/academy/(workspace)/[id]/dashboard/create/components/Third.tsx
  src/app/academy/(workspace)/[id]/dashboard/create/page.tsx
  src/app/academy/(workspace)/[id]/dashboard/page.tsx
  src/app/academy/(workspace)/[id]/market/@modal/(.)[challengeId]/page.tsx
  src/app/academy/(workspace)/[id]/market/[challengeId]/page.tsx
  src/app/academy/(workspace)/[id]/market/components/ChallengeCardList/index.tsx
  src/app/academy/(workspace)/[id]/market/components/ChallengeDetail/index.tsx
  src/app/academy/(workspace)/[id]/market/components/ModalDetail/index.tsx
  src/app/academy/(workspace)/[id]/market/page.tsx
  src/app/academy/(workspace)/[id]/members/detail/components/StudentDetailList/index.tsx
  src/app/academy/(workspace)/[id]/members/detail/page.tsx
  src/app/academy/(workspace)/[id]/members/instructor/components/InstructorDetailList/index.tsx
  src/app/academy/(workspace)/[id]/members/instructor/page.tsx
  src/app/academy/(workspace)/[id]/members/student/components/StudentDetailList/index.tsx
  src/app/academy/(workspace)/[id]/members/student/page.tsx
  src/app/academy/(workspace)/[id]/setting/page.tsx
  src/app/api/academy/students/route.ts
  src/app/api/challenge/create/route.ts
  src/app/api/challenge/delete/route.ts
  src/app/api/challenge/detail/route.ts
  src/app/api/challenge/student/approval/route.ts
  src/app/api/image/upload/route.ts
  src/app/api/market/release/route.ts
  src/features/academy/(workspace)/api/post-academy-challenges.ts
  src/features/academy/(workspace)/components/dashboard/ChallengeModal/First.tsx
  src/features/academy/(workspace)/components/dashboard/ChallengeModal/Second.tsx
  src/features/academy/(workspace)/components/dashboard/ChallengeModal/Third.tsx
  src/features/academy/(workspace)/components/dashboard/ChallengeModal/index.tsx
  src/features/academy/(workspace)/components/dashboard/Students/index.tsx
  src/features/academy/(workspace)/components/dashboard/academy-title/index.tsx
  src/features/academy/(workspace)/components/state-label/index.tsx
  src/features/academy/(workspace)/hooks/challenges/use-create-challenges.ts
  src/features/academy/(workspace)/utils/challengeState.ts
  src/shared/apis/academy.ts
  src/shared/apis/challenge.ts
  src/shared/apis/market.ts
  src/shared/constants/challenge-cataegrories.ts
  src/shared/enums/challenge.ts
  src/shared/hooks/academy/useGetInfiniteAcademyInstructorList.ts
  src/shared/hooks/academy/useGetInfiniteAcademyMemberDetailList.ts
  src/shared/hooks/academy/useGetInfiniteAcademyStudentList.ts
  src/shared/hooks/challenge/useDeleteChallenge.ts
  src/shared/hooks/images/use-get-presigned-url.ts
  src/shared/hooks/market/useReleaseChallenge.ts
  src/shared/hooks/use-step-progress.ts
  src/shared/types/acadmy.ts
  src/shared/types/images.ts
  src/shared/types/market.ts
  src/shared/utils/schema.ts
Labels: 🍠 deploy

#94 [CRAB-40] 챌린지 생성 오류 메세지 및 ui 수정
  src/app/academy/(workspace)/[id]/dashboard/components/MenuItem/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/create/components/First.tsx
  src/features/academy/(workspace)/components/dashboard/ChallengeMenu/index.tsx
  src/features/main/components/UserMenu/index.tsx
  src/shared/components/Button/index.tsx
  src/shared/components/CheckBox/index.tsx
  src/shared/utils/style.ts
  tailwind.config.ts
Labels: ✨ feature

#95 [Deploy] 2024년 11월 13일 Daily Deploy
  src/app/academy/(workspace)/[id]/dashboard/components/MenuItem/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/create/components/First.tsx
  src/features/academy/(workspace)/components/dashboard/ChallengeMenu/index.tsx
  src/features/main/components/UserMenu/index.tsx
  src/shared/components/Button/index.tsx
  src/shared/components/CheckBox/index.tsx
  src/shared/utils/style.ts
  tailwind.config.ts
Labels: 🍠 deploy

#98 [CRAB-42] 내 학원 목록, 디자인 변경 (AnimateCard, AnimateCardSkeleton 공용컴포넌트 구현)
  src/app/academy/(academy)/my/components/academy-list/index.tsx
  src/app/academy/(academy)/my/layout.tsx
  src/app/academy/(academy)/my/page.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/AnimateCard/index.tsx
  src/shared/components/Skeleton/Skeleton.tsx
Labels: ✨ feature

#100 [CRAB-41] 학생 대시보드 페이지 구현
  src/app/academy/(workspace)/[id]/dashboard/[challengeId]/page.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/(principal)/ChallengeDetail/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/(principal)/DashBoardUI/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/(student)/ChallengeDetail/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/(student)/DashBoardUI/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/(student)/MyChallengeDetail/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/AllChallengeContents/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/AnimateCard/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/ChallengeDetail/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/DetailTab/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/PlusChallengeCard/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/StudentAllChallengeContents/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/Toggle/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/page.tsx
  src/app/academy/(workspace)/[id]/layout.tsx
  src/app/academy/(workspace)/[id]/market/components/ChallengeCardList/index.tsx
  src/app/academy/(workspace)/[id]/market/components/ChallengeDetail/index.tsx
  src/app/academy/(workspace)/[id]/market/page.tsx
  src/app/academy/(workspace)/[id]/my-challenge/challenge/[studentChallengeId]/page.tsx
  src/app/academy/(workspace)/[id]/public-challenge/page.tsx
  src/features/academy/(workspace)/components/workspace-tab.tsx
  src/shared/apis/challenge.ts
  src/shared/constants/tab-menu.ts
  src/shared/hooks/challenge/useGetInfiniteStudentChallengeList.ts
  src/shared/hooks/challenge/useGetInfiniteTeacherChallengeList.ts
  src/shared/hooks/market/useGetInfiniteMarketChallenges.ts
  src/shared/types/acadmy.ts
Labels: ✨ feature

#104 [Deploy] 2024년 11월 15일 Daily Deploy
  eslint/default.js
  src/app/academy/(academy)/my/components/academy-list/index.tsx
  src/app/academy/(academy)/my/components/invitation-modal/components/Tab.tsx
  src/app/academy/(academy)/my/components/invitation-modal/index.tsx
  src/app/academy/(academy)/my/hooks/use-invitation-modal.ts
  src/app/academy/(academy)/my/layout.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/AnimateCard/index.tsx
  src/app/api/invitation/route.ts
  src/shared/apis/invitation.ts
  src/shared/components/Modal/index.tsx
  src/shared/components/Skeleton/Skeleton.tsx
  src/shared/hooks/invitation/useEnrollInvitation.ts
  src/shared/mocks/http.ts
  src/shared/types/invitation.ts
Labels: 🍠 deploy

#106 [CRAB-44] 학생 챌린지 상세 구현 및 공개 챌린지 ui 연결
  src/app/academy/(workspace)/[id]/dashboard/[challengeId]/page.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/(student)/MyChallengeDetail/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/DetailTab/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/MenuItem/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/Menubar/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/page.tsx
  src/app/academy/(workspace)/[id]/market/components/ChallengeCard/index.tsx
  src/app/academy/(workspace)/[id]/market/components/ChallengeTab/index.tsx
  src/app/academy/(workspace)/[id]/market/components/PublicChallengeLists/index.tsx
  src/app/academy/(workspace)/[id]/market/page.tsx
  src/app/academy/(workspace)/[id]/public-challenge/components/PublicCardList/index.tsx
  src/app/academy/(workspace)/[id]/public-challenge/page.tsx
  src/app/api/challenge/public/route.ts
  src/shared/apis/market.ts
  src/shared/apis/public.ts
  src/shared/components/Skeleton/Skeleton.tsx
  src/shared/constants/tab-menu.ts
  src/shared/hooks/market/useGetInfinitePublicChallenge.ts
  src/shared/hooks/public/useGetInfinitePublicChallenge.ts
  src/shared/types/market.ts
  src/shared/types/public.ts
Labels: ✨ feature

#109 [CRAB-46] 학생 대시보드 인증글 연결 & 인증글 작성
  public/images/icons/icon_bell.webp
  src/app/academy/(workspace)/[id]/dashboard/components/(student)/ChallengeDetail/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/(student)/CreateChallengeForm/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/(student)/MyChallenge/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/(student)/MyChallengeDetail/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/MyChallengeContentForm/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/StudentAllChallengeContents/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/StudentChallengeContent/index.tsx
  src/app/academy/(workspace)/[id]/market/components/ChallengeCardList/index.tsx
  src/app/academy/(workspace)/[id]/public-challenge/components/PublicCardList/index.tsx
  src/app/api/challenge/student/logs/my/route.ts
  src/app/api/challenge/student/logs/route.ts
  src/features/academy/(workspace)/components/state-label/index.tsx
  src/features/academy/(workspace)/hooks/use-image.ts
  src/shared/apis/challenge.ts
  src/shared/constants/query-keys.ts
  src/shared/constants/tab-menu.ts
  src/shared/hooks/challenge/useCreateChallengeContent.ts
  src/shared/hooks/challenge/useGetInfiniteAllChallengeContents.ts
  src/shared/hooks/challenge/useInfiniteMyChallengeContents.ts
  src/shared/types/acadmy.ts
  src/shared/types/market.ts
  src/shared/types/public.ts
Labels: ✨ feature

#111 [CRAB-47] 공개 챌린지 신청 및 상세보기
  src/app/academy/(workspace)/[id]/dashboard/components/(student)/MyChallenge/index.tsx
  src/app/academy/(workspace)/[id]/public-challenge/@modal/(.)[releasedId]/page.tsx
  src/app/academy/(workspace)/[id]/public-challenge/@modal/default.tsx
  src/app/academy/(workspace)/[id]/public-challenge/[releasedId]/page.tsx
  src/app/academy/(workspace)/[id]/public-challenge/components/PublicCardList/index.tsx
  src/app/academy/(workspace)/[id]/public-challenge/components/PublicDetail/index.tsx
  src/app/academy/(workspace)/[id]/public-challenge/components/PublicModal/index.tsx
  src/app/academy/(workspace)/[id]/public-challenge/layout.tsx
  src/app/api/challenge/public/route.ts
  src/features/academy/(workspace)/components/state-label/index.tsx
  src/shared/apis/market.ts
  src/shared/hooks/market/useApplyChallenge.ts
  src/shared/types/market.ts
  src/shared/types/public.ts
Labels: ✨ feature

#114 [Deploy] 2024년 11월 18일 Daily Deploy
  public/images/icons/icon_bell.webp
  src/app/academy/(workspace)/[id]/dashboard/components/(student)/ChallengeDetail/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/(student)/ChallengeFeed/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/(student)/CreateChallengeForm/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/(student)/MyChallenge/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/(student)/MyChallengeDetail/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/MyChallengeContentForm/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/StudentAllChallengeContents/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/StudentChallengeContent/index.tsx
  src/app/academy/(workspace)/[id]/feed/page.tsx
  src/app/academy/(workspace)/[id]/market/components/ChallengeCardList/index.tsx
  src/app/academy/(workspace)/[id]/public-challenge/@modal/(.)[releasedId]/page.tsx
  src/app/academy/(workspace)/[id]/public-challenge/@modal/default.tsx
  src/app/academy/(workspace)/[id]/public-challenge/[releasedId]/page.tsx
  src/app/academy/(workspace)/[id]/public-challenge/components/PublicCardList/index.tsx
  src/app/academy/(workspace)/[id]/public-challenge/components/PublicDetail/index.tsx
  src/app/academy/(workspace)/[id]/public-challenge/components/PublicModal/index.tsx
  src/app/academy/(workspace)/[id]/public-challenge/layout.tsx
  src/app/api/challenge/public/route.ts
  src/app/api/challenge/student/logs/my/route.ts
  src/app/api/challenge/student/logs/route.ts
  src/features/academy/(workspace)/components/state-label/index.tsx
  src/features/academy/(workspace)/components/workspace-tab.tsx
  src/features/academy/(workspace)/hooks/use-image.ts
  src/shared/apis/challenge.ts
  src/shared/apis/market.ts
  src/shared/constants/query-keys.ts
  src/shared/constants/tab-menu.ts
  src/shared/hooks/challenge/useCreateChallengeContent.ts
  src/shared/hooks/challenge/useGetInfiniteAllChallengeContents.ts
  src/shared/hooks/challenge/useGetInfiniteFeedChallengeContents.ts
  src/shared/hooks/challenge/useInfiniteMyChallengeContents.ts
  src/shared/hooks/market/useApplyChallenge.ts
  src/shared/types/acadmy.ts
  src/shared/types/market.ts
  src/shared/types/public.ts
Labels: 🍠 deploy

#117 [CRAB-50] 원장 대시보드 수정
  public/images/icons/icon_speaker.webp
  src/app/academy/(workspace)/[id]/dashboard/components/ChallengeStatistics/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/StudentCardList/index.tsx
  src/app/api/challenge/student/approval/route.ts
  src/shared/apis/challenge.ts
Labels: ✨ feature

#119 [CRAB-51] 원장/강사 대시보드 수정
  src/app/academy/(academy)/my/components/academy-list/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/(principal)/DashBoardUI/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/AllChallengeContents/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/AnimateCard/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/MenuItem/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/Menubar/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/PlusChallengeCard/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/page.tsx
  src/app/api/challenge/list/route.ts
  src/shared/apis/challenge.ts
  src/shared/hooks/challenge/useGetInfiniteTeacherChallengeList.ts
  src/shared/hooks/useDebounce.ts
Labels: ✨ feature

#121 [CRAB-52] 학생 대시보드 검색어 및 카테고리 처리
  src/app/academy/(workspace)/[id]/dashboard/components/(student)/DashBoardUI/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/Menubar/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/StudentAllChallengeContents/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/page.tsx
  src/app/api/challenge/list/route.ts
  src/app/api/challenge/student/list/route.ts
  src/shared/apis/challenge.ts
  src/shared/constants/tab-menu.ts
  src/shared/hooks/challenge/useGetInfiniteStudentChallengeList.ts
Labels: ✨ feature

#124 [CRAB-54] 배포 챌린지 description 추가
  src/app/academy/(workspace)/[id]/dashboard/components/(student)/MyChallengeDetail/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/ChallengeDetail/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/Toggle/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/create/components/First.tsx
  src/app/academy/(workspace)/[id]/dashboard/create/components/Second.tsx
  src/app/academy/(workspace)/[id]/dashboard/create/components/Third.tsx
  src/app/academy/(workspace)/[id]/dashboard/create/page.tsx
  src/app/academy/(workspace)/[id]/market/components/ChallengeContent/index.tsx
  src/app/academy/(workspace)/[id]/market/components/ChallengeDetail/index.tsx
  src/app/academy/(workspace)/[id]/market/components/ModalContent/index.tsx
  src/app/academy/(workspace)/[id]/market/components/ModalDetail/index.tsx
  src/app/academy/(workspace)/[id]/market/components/Release/First.tsx
  src/app/academy/(workspace)/[id]/market/components/Release/Second.tsx
  src/shared/apis/challenge.ts
  src/shared/components/BoxContainer/index.tsx
  src/shared/components/ProgressBar/index.tsx
  src/shared/hooks/use-step-progress.ts
  src/shared/hooks/useHandleStepChallenge.ts
  src/shared/types/acadmy.ts
  src/shared/types/market.ts
Labels: ✨ feature

#125 [CRAB-53] 챌린지 피드 ui 수정
  src/app/academy/(workspace)/[id]/dashboard/components/(student)/ChallengeFeed/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/StudentChallengeContent/index.tsx
  src/app/academy/(workspace)/[id]/feed/page.tsx
Labels: ✨ feature

#127 [CRAB-55] 공개 챌린지 UI 수정
  src/app/academy/(workspace)/[id]/public-challenge/components/PublicCardList/index.tsx
  src/app/academy/(workspace)/[id]/public-challenge/components/PublicDetail/index.tsx
  src/app/academy/(workspace)/[id]/public-challenge/components/PublicModal/index.tsx
  src/shared/types/public.ts
Labels: ✨ feature

#128 [CRAB-49] 마이페이지 구현
  src/app/api/auth/profile/route.ts
  src/app/profile/@sidebar/page.tsx
  src/app/profile/components/LinkBox/index.tsx
  src/app/profile/components/ProfileBox/index.tsx
  src/app/profile/components/ProfileEditForm/index.tsx
  src/app/profile/delete/page.tsx
  src/app/profile/layout.tsx
  src/app/profile/page.tsx
  src/app/profile/password/page.tsx
  src/features/main/components/UserMenu/index.tsx
  src/shared/apis/invitation.ts
  src/shared/apis/profile.ts
  src/shared/components/Avatar/index.tsx
  src/shared/enums/auth.ts
  src/shared/hooks/main/useGetProfile.ts
  src/shared/hooks/profile/useEditProfile.ts
  src/shared/types/auth.ts
  tailwind.config.ts
Labels: ✨ feature

#133 [CRAB-56] Refresh Token 로직 수정
  src/app/academy/(workspace)/[id]/dashboard/page.tsx
  src/app/academy/(workspace)/[id]/layout.tsx
Labels: 🐛 bug

#134 [Deploy] 2024년 11월 22일 Daily Deploy
  package.json
  src/app/academy/(academy)/my/components/invitation-modal/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/page.tsx
  src/app/academy/(workspace)/[id]/layout.tsx
  src/app/api/invitation/route.ts
  src/features/academy/(workspace)/components/workspace-tab.tsx
  src/middleware.ts
  src/shared/apis/fetch-data.ts
  src/shared/components/QueryProvider/index.tsx
  src/shared/utils/decoded-token.ts
  yarn.lock
Labels: 🍠 deploy

#143 [CRAB-58] 챌린지 피드 상세
  src/app/academy/(workspace)/[id]/dashboard/components/(student)/ChallengeFeed/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/(student)/MyChallenge/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/StudentChallengeContent/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/StudentChallengeContents/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/page.tsx
  src/app/academy/(workspace)/[id]/feed/[feedId]/@comment/page.tsx
  src/app/academy/(workspace)/[id]/feed/[feedId]/@detail/page.tsx
  src/app/academy/(workspace)/[id]/feed/[feedId]/layout.tsx
  src/app/academy/(workspace)/[id]/feed/components/ChallengeDetail/index.tsx
  src/app/academy/(workspace)/[id]/feed/components/CommentForm/index.tsx
  src/shared/types/acadmy.ts
  tailwind.config.ts
Labels: ✨ feature

#144 [Deploy] 2024년 11월 25일 Daily Deploy
  src/app/academy/(workspace)/[id]/dashboard/components/(student)/ChallengeFeed/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/(student)/MyChallenge/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/StudentChallengeContent/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/StudentChallengeContents/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/page.tsx
  src/app/academy/(workspace)/[id]/feed/[feedId]/@comment/page.tsx
  src/app/academy/(workspace)/[id]/feed/[feedId]/@detail/page.tsx
  src/app/academy/(workspace)/[id]/feed/[feedId]/layout.tsx
  src/app/academy/(workspace)/[id]/feed/components/ChallengeDetail/index.tsx
  src/app/academy/(workspace)/[id]/feed/components/CommentForm/index.tsx
  src/shared/types/acadmy.ts
  tailwind.config.ts
Labels: ✨ feature

#147 [CRAB-62] 학원 생성 신청 (이메일 인증 포함) 구현, 번호 양식 자동화 인풋 생성.
  src/app/space/enroll/page.tsx
  src/features/space/enroll/components/form.tsx
  src/features/space/enroll/components/phone-input.tsx
  src/shared/components/AddressSearch/address-search.tsx
  src/shared/components/Footer/index.tsx
Labels: 🐛 bug, ✨ feature

#152 [CRAB-63] 댓글 조회 api 연결
  src/app/academy/(workspace)/[id]/feed/[feedId]/@comment/page.tsx
  src/app/academy/(workspace)/[id]/feed/components/ChallengeDetail/index.tsx
  src/app/academy/(workspace)/[id]/feed/components/Comment/index.tsx
  src/app/academy/(workspace)/[id]/feed/components/CommentForm/index.tsx
  src/app/academy/(workspace)/[id]/feed/components/CommentList/index.tsx
  src/app/academy/(workspace)/[id]/public-challenge/components/PublicDetail/index.tsx
  src/app/academy/(workspace)/[id]/public-challenge/components/PublicModal/index.tsx
  src/app/api/academy/profile/route.ts
  src/app/api/comment/route.ts
  src/shared/apis/academy.ts
  src/shared/apis/comments.ts
  src/shared/constants/query-keys.ts
  src/shared/enums/comment.ts
  src/shared/hooks/academy/useGetAcademyProfile.ts
  src/shared/hooks/comments/useCreateComment.ts
  src/shared/hooks/comments/useGetInfiniteComments.ts
  src/shared/types/comment.ts
Labels: ✨ feature

#155 [CRAB-65] 댓글 신고, 대댓글 api 연결
  src/app/academy/(workspace)/[id]/feed/[feedId]/@comment/page.tsx
  src/app/academy/(workspace)/[id]/feed/components/Comment/index.tsx
  src/app/academy/(workspace)/[id]/feed/components/CommentForm/index.tsx
  src/app/academy/(workspace)/[id]/feed/components/CommentList/index.tsx
  src/app/api/comment/report/route.ts
  src/shared/apis/comments.ts
  src/shared/hooks/comments/useReportComment.ts
  src/shared/types/comment.ts
Labels: ✨ feature

#156 [Deploy] 2024년 11월 27일 Daily Deploy
  src/app/academy/(academy)/my/components/academy-list/index.tsx
  src/app/academy/(academy)/my/components/invitation-modal/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/ChallengeDetail/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/StudentCard/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/StudentChallengeContent/index.tsx
  src/app/academy/(workspace)/[id]/feed/[feedId]/@comment/page.tsx
  src/app/academy/(workspace)/[id]/feed/components/ChallengeDetail/index.tsx
  src/app/academy/(workspace)/[id]/feed/components/Comment/index.tsx
  src/app/academy/(workspace)/[id]/feed/components/CommentForm/index.tsx
  src/app/academy/(workspace)/[id]/feed/components/CommentList/index.tsx
  src/app/academy/(workspace)/[id]/layout.tsx
  src/app/academy/(workspace)/[id]/market/components/ChallengeContent/index.tsx
  src/app/academy/(workspace)/[id]/market/components/ModalContent/index.tsx
  src/app/academy/(workspace)/[id]/public-challenge/components/PublicDetail/index.tsx
  src/app/academy/(workspace)/[id]/public-challenge/components/PublicModal/index.tsx
  src/app/academy/(workspace)/[id]/setting/components/setting-list/index.tsx
  src/app/api/academy/list/route.ts
  src/app/api/academy/manage/admin/students/route.ts
  src/app/api/academy/manage/instructors/route.ts
  src/app/api/academy/manage/students/route.ts
  src/app/api/academy/profile/route.ts
  src/app/api/auth/profile/route.ts
  src/app/api/comment/report/route.ts
  src/app/api/comment/route.ts
  src/features/academy/my/api/get-participate-academy-list.mock.ts
  src/shared/apis/academy.ts
  src/shared/apis/challenge.ts
  src/shared/apis/comments.ts
  src/shared/apis/fetch-data.ts
  src/shared/constants/query-keys.ts
  src/shared/enums/comment.ts
  src/shared/hooks/academy/useGetAcademyProfile.ts
  src/shared/hooks/comments/useCreateComment.ts
  src/shared/hooks/comments/useGetInfiniteComments.ts
  src/shared/hooks/comments/useReportComment.ts
  src/shared/types/acadmy.ts
  src/shared/types/comment.ts
  src/shared/types/market.ts
  src/shared/types/public.ts
Labels: 🍠 deploy

#160 [CRAB-66] 댓글 차단 api 연결
  src/app/academy/(workspace)/[id]/feed/components/Comment/index.tsx
  src/app/academy/(workspace)/[id]/feed/components/CommentIcon/index.tsx
  src/app/academy/(workspace)/[id]/feed/components/CommentList/index.tsx
  src/app/api/comment/block/route.ts
  src/shared/apis/comments.ts
  src/shared/hooks/comments/useBlockComment.ts
  src/shared/types/comment.ts
Labels: ✨ feature

#161 [Deploy] 2024년 11월 27일 Daily Deploy
  src/app/academy/(workspace)/[id]/feed/components/Comment/index.tsx
  src/app/academy/(workspace)/[id]/feed/components/CommentIcon/index.tsx
  src/app/academy/(workspace)/[id]/feed/components/CommentList/index.tsx
  src/app/academy/(workspace)/[id]/invitation/components/Invitation/index.tsx
  src/app/api/academy/invitation/route.ts
  src/app/api/comment/block/route.ts
  src/shared/apis/comments.ts
  src/shared/apis/invitation.ts
  src/shared/hooks/comments/useBlockComment.ts
  src/shared/types/comment.ts
Labels: 🍠 deploy

#163 [CRAB-68] 대시보드 학원 정보 변경
  src/app/academy/(workspace)/[id]/dashboard/page.tsx
Labels: ✨ feature

#167 [CRAB-69] 댓글 삭제하기
  src/app/academy/(workspace)/[id]/feed/components/Comment/index.tsx
  src/app/api/comment/route.ts
  src/shared/apis/comments.ts
  src/shared/components/Button/index.tsx
  src/shared/components/SmallModal/index.tsx
  src/shared/hooks/comments/useDeleteComment.ts
  src/shared/types/comment.ts
Labels: ✨ feature

#169 [CRAB-71] 학생 자신의 챌린지 상세 UI 수정
  src/app/academy/(workspace)/[id]/dashboard/components/(student)/CreateChallengeForm/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/(student)/MyChallenge/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/(student)/MyChallengeDetail/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/StudentChallengeContent/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/Toggle/index.tsx
  src/shared/hooks/challenge/useCreateChallengeContent.ts
Labels: ✨ feature

#173 [CRAB-74] useManageAcademy Hook 생성
  eslint/default.js
  src/shared/apis/academy.ts
  src/shared/apis/fetch-data.ts
  src/shared/constants/query-keys.ts
  src/shared/hooks/academy/useManageAcademy.ts
Labels: ✨ feature

#174 [CRAB-73] 학원 설정페이지 구현
  src/app/academy/(workspace)/[id]/setting/components/SettingBar/index.tsx
  src/app/academy/(workspace)/[id]/setting/components/SettingInfo/index.tsx
  src/app/academy/(workspace)/[id]/setting/layout.tsx
  src/app/academy/(workspace)/[id]/setting/management/academy/page.tsx
  src/app/academy/(workspace)/[id]/setting/management/instructor/page.tsx
  src/app/academy/(workspace)/[id]/setting/management/student/page.tsx
  src/app/academy/(workspace)/[id]/setting/page.tsx
  src/shared/components/ProfileCard/index.tsx
Labels: ✨ feature

#175 [CRAB-72] 마이페이지 탈퇴 모달 수정
  src/app/profile/components/DeleteForm/index.tsx
  src/shared/hooks/main/useGetProfile.ts
Labels: ✨ feature

#176 [Deploy] 2024년 11월 28일 Daily Deploy
  eslint/default.js
  src/app/academy/(workspace)/[id]/dashboard/components/(student)/CreateChallengeForm/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/(student)/MyChallenge/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/(student)/MyChallengeDetail/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/StudentChallengeContent/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/Toggle/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/page.tsx
  src/app/academy/(workspace)/[id]/feed/components/Comment/index.tsx
  src/app/academy/(workspace)/[id]/members/detail/components/StudentDetailList/index.tsx
  src/app/academy/(workspace)/[id]/setting/components/SettingBar/index.tsx
  src/app/academy/(workspace)/[id]/setting/components/SettingInfo/index.tsx
  src/app/academy/(workspace)/[id]/setting/layout.tsx
  src/app/academy/(workspace)/[id]/setting/management/academy/page.tsx
  src/app/academy/(workspace)/[id]/setting/management/instructor/page.tsx
  src/app/academy/(workspace)/[id]/setting/management/student/page.tsx
  src/app/academy/(workspace)/[id]/setting/page.tsx
  src/app/api/comment/route.ts
  src/app/api/manage/academy/challenge/route.ts
  src/app/api/manage/academy/route.ts
  src/app/api/manage/instructor/edit/route.ts
  src/app/api/manage/instructor/revoke/route.ts
  src/app/api/manage/student/edit/route.ts
  src/app/api/manage/student/revoke/route.ts
  src/app/profile/components/DeleteForm/index.tsx
  src/shared/apis/academy.ts
  src/shared/apis/comments.ts
  src/shared/apis/fetch-data.ts
  src/shared/components/Button/index.tsx
  src/shared/components/ProfileCard/index.tsx
  src/shared/components/SmallModal/index.tsx
  src/shared/constants/query-keys.ts
  src/shared/hooks/academy/useManageAcademy.ts
  src/shared/hooks/challenge/useCreateChallengeContent.ts
  src/shared/hooks/comments/useDeleteComment.ts
  src/shared/hooks/main/useGetProfile.ts
  src/shared/types/comment.ts
  src/shared/types/manage.ts
Labels: 🍠 deploy

#178 [CRAB-75] 챌린지 상세 레이아웃 수정
  src/app/academy/(workspace)/[id]/dashboard/components/ChallengeDetail/index.tsx
  src/app/academy/(workspace)/[id]/market/components/ChallengeContent/index.tsx
Labels: ✨ feature

#181 [CRAB-77] Protected Route 적용
  src/app/academy/(academy)/my/layout.tsx
  src/app/academy/(academy)/my/page.tsx
  src/app/academy/(workspace)/[id]/layout.tsx
  src/middleware.ts
Labels: 🐛 bug

#184 [CRAB-78] 포인트가 노출되지 않는 현상 해결, 천 단위 숫자 포맷팅
  src/app/academy/(workspace)/[id]/dashboard/components/(student)/MyChallengeDetail/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/BestStudentTableContent/index.tsx
  src/app/academy/(workspace)/[id]/public-challenge/components/PublicDetail/index.tsx
  src/app/academy/(workspace)/[id]/public-challenge/components/PublicModal/index.tsx
  src/app/api/auth/login/route.ts
  src/shared/components/ProfileCard/index.tsx
  src/shared/utils/number.ts
Labels: 🐛 bug, ✨ feature

#185 [CRAB-76] 설정 페이지 학생/강사 관리 연결
  src/app/academy/(workspace)/[id]/members/detail/components/StudentDetailList/index.tsx
  src/app/academy/(workspace)/[id]/members/instructor/components/InstructorDetailList/index.tsx
  src/app/academy/(workspace)/[id]/members/student/components/StudentDetailList/index.tsx
  src/app/academy/(workspace)/[id]/setting/components/InstructorList/index.tsx
  src/app/academy/(workspace)/[id]/setting/components/InstructorStudentList/index.tsx
  src/app/academy/(workspace)/[id]/setting/components/PrincipalStudentList/index.tsx
  src/app/academy/(workspace)/[id]/setting/layout.tsx
  src/app/academy/(workspace)/[id]/setting/management/instructor/[memberId]/page.tsx
  src/app/academy/(workspace)/[id]/setting/management/instructor/page.tsx
  src/app/academy/(workspace)/[id]/setting/management/student/[memberId]/page.tsx
  src/app/academy/(workspace)/[id]/setting/management/student/components/MemberDetail/index.tsx
  src/app/academy/(workspace)/[id]/setting/management/student/page.tsx
  src/app/api/academy/manage/admin/students/route.ts
  src/features/academy/(workspace)/components/dashboard/Students/index.tsx
  src/shared/components/FramerScale/index.tsx
  src/shared/components/ProfileCard/index.tsx
  src/shared/components/Textarea/index.tsx
  src/shared/hooks/academy/useGetInfiniteAcademyInstructorList.ts
  src/shared/types/acadmy.ts
Labels: ✨ feature

#186 [Deploy] 2024년 11월 29일 Daily Deploy
  src/app/academy/(workspace)/[id]/dashboard/components/(student)/MyChallengeDetail/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/BestStudentTableContent/index.tsx
  src/app/academy/(workspace)/[id]/members/detail/components/StudentDetailList/index.tsx
  src/app/academy/(workspace)/[id]/members/instructor/components/InstructorDetailList/index.tsx
  src/app/academy/(workspace)/[id]/members/student/components/StudentDetailList/index.tsx
  src/app/academy/(workspace)/[id]/public-challenge/components/PublicDetail/index.tsx
  src/app/academy/(workspace)/[id]/public-challenge/components/PublicModal/index.tsx
  src/app/academy/(workspace)/[id]/setting/components/InstructorList/index.tsx
  src/app/academy/(workspace)/[id]/setting/components/InstructorStudentList/index.tsx
  src/app/academy/(workspace)/[id]/setting/components/PrincipalStudentList/index.tsx
  src/app/academy/(workspace)/[id]/setting/layout.tsx
  src/app/academy/(workspace)/[id]/setting/management/instructor/[memberId]/page.tsx
  src/app/academy/(workspace)/[id]/setting/management/instructor/page.tsx
  src/app/academy/(workspace)/[id]/setting/management/student/[memberId]/page.tsx
  src/app/academy/(workspace)/[id]/setting/management/student/components/MemberDetail/index.tsx
  src/app/academy/(workspace)/[id]/setting/management/student/page.tsx
  src/app/api/academy/manage/admin/students/route.ts
  src/app/api/auth/login/route.ts
  src/features/academy/(workspace)/components/dashboard/Students/index.tsx
  src/shared/components/FramerScale/index.tsx
  src/shared/components/ProfileCard/index.tsx
  src/shared/components/Textarea/index.tsx
  src/shared/hooks/academy/useGetInfiniteAcademyInstructorList.ts
  src/shared/types/acadmy.ts
  src/shared/utils/number.ts
Labels: 🍠 deploy

#189 [CRAB-80] 학원 등록, 서버 변경사항 반영 및 UI 변경, 이메일 인증하기 플로우 변경
  src/app/profile/components/EmailForm/index.tsx
  src/app/profile/components/PasswordForm/index.tsx
  src/app/profile/components/ProfileEditForm/index.tsx
  src/features/space/enroll/components/form.tsx
Labels: 🐛 bug, ✨ feature

#190 [CRAB-79] 설정 학생 상세 연결
  src/app/academy/(workspace)/[id]/setting/components/InstructorStudentList/index.tsx
  src/app/academy/(workspace)/[id]/setting/components/StudentList/index.tsx
  src/app/academy/(workspace)/[id]/setting/management/student/[memberId]/page.tsx
  src/app/academy/(workspace)/[id]/setting/management/student/components/MemberDetail/index.tsx
  src/app/academy/(workspace)/[id]/setting/management/student/page.tsx
  src/app/api/manage/student/edit/route.ts
  src/app/api/manage/student/route.ts
  src/shared/apis/academy.ts
  src/shared/components/FramerScale/index.tsx
  src/shared/components/Input/index.tsx
  src/shared/components/ProfileCard/index.tsx
  src/shared/components/SmallModal/index.tsx
  src/shared/components/Textarea/index.tsx
  src/shared/constants/query-keys.ts
  src/shared/hooks/academy/useGetStudentDetail.ts
  src/shared/hooks/academy/useManageAcademy.ts
  src/shared/types/acadmy.ts
Labels: ✨ feature

#191 [Deploy] 2024년 11월 29일 Daily Deploy
  src/app/academy/(workspace)/[id]/setting/components/StudentList/index.tsx
  src/app/academy/(workspace)/[id]/setting/management/student/[memberId]/page.tsx
  src/app/academy/(workspace)/[id]/setting/management/student/components/MemberDetail/index.tsx
  src/app/academy/(workspace)/[id]/setting/management/student/page.tsx
  src/app/api/manage/student/edit/route.ts
  src/app/api/manage/student/route.ts
  src/app/profile/components/EmailForm/index.tsx
  src/app/profile/components/PasswordForm/index.tsx
  src/app/profile/components/ProfileEditForm/index.tsx
  src/features/space/enroll/components/form.tsx
  src/shared/apis/academy.ts
  src/shared/components/FramerScale/index.tsx
  src/shared/components/Input/index.tsx
  src/shared/components/ProfileCard/index.tsx
  src/shared/components/SmallModal/index.tsx
  src/shared/components/Textarea/index.tsx
  src/shared/constants/query-keys.ts
  src/shared/hooks/academy/useGetStudentDetail.ts
  src/shared/hooks/academy/useManageAcademy.ts
  src/shared/types/acadmy.ts
Labels: ✨ feature
