Repository crabit-official/Crabit-FE2, pull requests merged in 2024-10, with the labels that each got.

#4 [Docs] pr & issue 템플릿 설정
  .github/ISSUE_TEMPLATE/etc.md
  .github/ISSUE_TEMPLATE/✨-feature.md
  .github/ISSUE_TEMPLATE/🐛-bug-report.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 📝 docs

#5 [ci/cd]: create jira issue template
  .github/workflows/create_jira_issue.yml
  commitlint.config.cjs
Labels: 🌐 ci/cd

#8 [CRAB-3] Header 컴포넌트 구현 / 모달 컴포넌트 구현
  eslint/tailwindcss.js
  eslint/typescript.js
  package.json
  src/app/layout.tsx
  src/features/main/components/Container/index.tsx
  src/features/main/components/LoginModal/index.tsx
  src/features/main/components/MenuItem/index.tsx
  src/features/main/components/Navbar/index.tsx
  src/features/main/components/RegisterModal/index.tsx
  src/features/main/components/UserMenu/index.tsx
  src/features/main/hooks/use-login-modal.ts
  src/features/main/hooks/use-register-modal.ts
  src/features/main/hooks/use-scroll-top.ts
  src/shared/components/Avatar/index.tsx
  src/shared/components/Heading/index.tsx
  src/shared/components/Input/index.tsx
  src/shared/components/Logo/index.tsx
  src/shared/components/Modal/index.tsx
  yarn.lock
Labels: ✨ feature

#11 [CRAB-6] My Academy Page Folder Structure
  next.config.mjs
  package.json
  src/app/academy/alert/page.tsx
  src/app/academy/layout.tsx
  src/app/academy/my/page.tsx
  src/app/academy/setting/page.tsx
  src/app/layout.tsx
  src/app/page.tsx
  src/features/academy/components/academy-tab.tsx
  src/features/academy/components/tab-button.tsx
  src/features/academy/my/api/get-participate-academy-list.mock.ts
  src/features/academy/my/components/row-card.tsx
  src/features/main/components/Navbar/index.tsx
  src/features/main/components/UserMenu/index.tsx
  src/shared/components/Button/index.tsx
  src/shared/components/Flex/index.tsx
  src/shared/components/MSWProvider/index.tsx
  src/shared/constants/api.ts
  src/shared/mocks/handler.ts
  src/shared/mocks/http.ts
  src/shared/mocks/index.ts
  src/shared/styles/globals.css
  yarn.lock
Labels: ✨ feature

#12 [CRAB-6] main 페이지 ui 구현
  public/images/banner_background.webp
  public/images/logo_accomplishment.webp
  public/images/logo_calendar.webp
  public/images/logo_goal.webp
  public/images/logo_ncs.webp
  src/app/layout.tsx
  src/app/page.tsx
  src/features/main/SecondBanner/index.tsx
  src/features/main/components/ChallengeCard/index.tsx
  src/features/main/components/FifthBanner/index.tsx
  src/features/main/components/FourthBanner/index.tsx
  src/features/main/components/MainBanner/index.tsx
  src/features/main/components/MainCard/index.tsx
  src/features/main/components/ScholarshipCard/index.tsx
  src/features/main/components/ThirdBanner/index.tsx
  src/shared/components/Footer/index.tsx
  src/shared/constants/main-cards.ts
Labels: ✨ feature

#13 [Deploy] 2024년 10월 16일 Daily Deploy
  eslint/tailwindcss.js
  eslint/typescript.js
  next.config.mjs
  package.json
  public/images/banner_background.webp
  public/images/logo_accomplishment.webp
  public/images/logo_calendar.webp
  public/images/logo_goal.webp
  public/images/logo_ncs.webp
  src/app/academy/alert/page.tsx
  src/app/academy/layout.tsx
  src/app/academy/my/page.tsx
  src/app/academy/setting/page.tsx
  src/app/layout.tsx
  src/app/page.tsx
  src/features/academy/components/academy-tab.tsx
  src/features/academy/components/tab-button.tsx
  src/features/academy/my/api/get-participate-academy-list.mock.ts
  src/features/academy/my/components/row-card.tsx
  src/features/main/SecondBanner/index.tsx
  src/features/main/components/ChallengeCard/index.tsx
  src/features/main/components/Container/index.tsx
  src/features/main/components/FifthBanner/index.tsx
  src/features/main/components/FourthBanner/index.tsx
  src/features/main/components/LoginModal/index.tsx
  src/features/main/components/MainBanner/index.tsx
  src/features/main/components/MainCard/index.tsx
  src/features/main/components/MenuItem/index.tsx
  src/features/main/components/Navbar/index.tsx
  src/features/main/components/RegisterModal/index.tsx
  src/features/main/components/ScholarshipCard/index.tsx
  src/features/main/components/ThirdBanner/index.tsx
  src/features/main/components/UserMenu/index.tsx
  src/features/main/hooks/use-login-modal.ts
  src/features/main/hooks/use-register-modal.ts
  src/features/main/hooks/use-scroll-top.ts
  src/shared/components/Avatar/index.tsx
  src/shared/components/Button/index.tsx
  src/shared/components/Flex/index.tsx
  src/shared/components/Footer/index.tsx
  src/shared/components/Heading/index.tsx
  src/shared/components/Input/index.tsx
  src/shared/components/Logo/index.tsx
  src/shared/components/MSWProvider/index.tsx
  src/shared/components/Modal/index.tsx
  src/shared/constants/api.ts
  src/shared/constants/main-cards.ts
  src/shared/mocks/handler.ts
  src/shared/mocks/http.ts
  src/shared/mocks/index.ts
  src/shared/styles/globals.css
  yarn.lock
Labels: 🍠 deploy

#16 [CRAB-7] 로그인 nextauth 연결
  src/app/api/auth/[...nextauth]/route.ts
  src/app/layout.tsx
  src/features/main/components/LoginModal/index.tsx
  src/features/main/components/RegisterModal/index.tsx
  src/features/main/components/UserMenu/index.tsx
  src/shared/libs/axios-instance.ts
  src/shared/libs/next-auth/auth-provider.tsx
  src/shared/libs/next-auth/session-provider.tsx
  src/shared/types/next-auth.d.ts
  src/shared/types/profile.ts
  src/shared/utils/authOptions.ts
  tsconfig.json
  yarn.lock
Labels: ✨ feature

#17 [CRAB-8] 기관 등록하기 페이지 구현
  package.json
  src/app/layout.tsx
  src/app/space/enroll/page.tsx
  src/features/space/enroll/components/form.tsx
  src/shared/components/AddressSearch/address-search.tsx
  src/shared/components/Heading/index.tsx
  src/shared/components/Input/index.tsx
  src/shared/components/Spacing/spacing.tsx
  src/shared/type/register.ts
  yarn.lock
Labels: ✨ feature

#20 [CRAB-10] 학원 워크스페이스 폴더 구조 및 레이아웃 설정
  src/app/academy/(academy)/alert/page.tsx
  src/app/academy/(academy)/layout.tsx
  src/app/academy/(academy)/my/page.tsx
  src/app/academy/(academy)/setting/page.tsx
  src/app/academy/(workspace)/[id]/challenge/page.tsx
  src/app/academy/(workspace)/[id]/dashboard/page.tsx
  src/app/academy/(workspace)/[id]/manage/page.tsx
  src/app/academy/(workspace)/[id]/setting/page.tsx
  src/app/academy/(workspace)/layout.tsx
  src/app/layout.tsx
  src/features/academy/(academy)/components/academy-tab.tsx
  src/features/academy/(workspace)/components/workspace-tab.tsx
Labels: ✨ feature

#21 [Deploy] 2024년 10월 17일 Daily Deploy
  package.json
  src/app/academy/(academy)/alert/page.tsx
  src/app/academy/(academy)/layout.tsx
  src/app/academy/(academy)/my/page.tsx
  src/app/academy/(academy)/setting/page.tsx
  src/app/academy/(workspace)/[id]/challenge/page.tsx
  src/app/academy/(workspace)/[id]/dashboard/page.tsx
  src/app/academy/(workspace)/[id]/manage/page.tsx
  src/app/academy/(workspace)/[id]/setting/page.tsx
  src/app/academy/(workspace)/layout.tsx
  src/app/api/auth/[...nextauth]/route.ts
  src/app/layout.tsx
  src/app/space/enroll/page.tsx
  src/features/academy/(academy)/components/academy-tab.tsx
  src/features/academy/(workspace)/components/workspace-tab.tsx
  src/features/main/components/LoginModal/index.tsx
  src/features/main/components/RegisterModal/index.tsx
  src/features/main/components/UserMenu/index.tsx
  src/features/space/enroll/components/form.tsx
  src/shared/components/AddressSearch/address-search.tsx
  src/shared/components/Heading/index.tsx
  src/shared/components/Input/index.tsx
  src/shared/components/Spacing/spacing.tsx
  src/shared/libs/axios-instance.ts
  src/shared/libs/next-auth/auth-provider.tsx
  src/shared/libs/next-auth/session-provider.tsx
  src/shared/type/register.ts
  src/shared/types/next-auth.d.ts
  src/shared/types/profile.ts
  src/shared/utils/authOptions.ts
  tsconfig.json
  yarn.lock
Labels: 🍠 deploy

#23 [CRAB-9] checkbox 컴포넌트 생성 및 auth 수정
  .gitignore
  package.json
  src/features/main/components/LoginModal/index.tsx
  src/features/main/components/RegisterModal/index.tsx
  src/features/main/components/UserMenu/index.tsx
  src/shared/components/CheckBox/index.tsx
  src/shared/libs/next-auth/auth-provider.tsx
  src/shared/types/next-auth.d.ts
  src/shared/types/profile.ts
  src/shared/utils/authOptions.ts
  src/shared/utils/schema.ts
  yarn.lock
Labels: ✨ feature

#25 [CRAB-11] 내 학원, 학원 알림 페이지 구현
  src/app/academy/(academy)/alert/page.tsx
  src/app/academy/(academy)/my/layout.tsx
  src/app/academy/(academy)/my/page.tsx
  src/features/academy/alert/components/ListRow.tsx
  src/features/academy/my/components/RowCard/row-card.tsx
  src/features/academy/my/components/Sidebar/menu.tsx
  src/features/academy/my/components/Sidebar/mobile-menu.tsx
  src/features/academy/my/components/Sidebar/side-bar.tsx
  src/features/main/components/Container/index.tsx
  src/shared/components/Flex/index.tsx
  yarn.lock
Labels: ✨ feature

#27 [Deploy] 2024년 10월 19일 Daily Deploy
  .gitignore
  next.config.mjs
  package.json
  src/app/academy/(academy)/alert/page.tsx
  src/app/academy/(academy)/my/layout.tsx
  src/app/academy/(academy)/my/page.tsx
  src/app/academy/(workspace)/[id]/dashboard/@modal/(.)[contentId]/page.tsx
  src/app/academy/(workspace)/[id]/dashboard/@modal/default.tsx
  src/app/academy/(workspace)/[id]/dashboard/[contentId]/page.tsx
  src/app/academy/(workspace)/[id]/dashboard/layout.tsx
  src/app/academy/(workspace)/[id]/dashboard/page.tsx
  src/app/academy/(workspace)/layout.tsx
  src/features/academy/(workspace)/components/dashboard/ChallengeMenu/index.tsx
  src/features/academy/(workspace)/components/dashboard/Content/index.tsx
  src/features/academy/(workspace)/components/dashboard/Profile/index.tsx
  src/features/academy/(workspace)/components/dashboard/Sidebar/index.tsx
  src/features/academy/(workspace)/components/dashboard/Trendbar/index.tsx
  src/features/academy/alert/components/ListRow.tsx
  src/features/academy/components/academy-tab.tsx
  src/features/academy/my/components/RowCard/row-card.tsx
  src/features/academy/my/components/Sidebar/menu.tsx
  src/features/academy/my/components/Sidebar/mobile-menu.tsx
  src/features/academy/my/components/Sidebar/side-bar.tsx
  src/features/main/components/Container/index.tsx
  src/features/main/components/LoginModal/index.tsx
  src/features/main/components/RegisterModal/index.tsx
  src/features/main/components/UserMenu/index.tsx
  src/shared/components/CheckBox/index.tsx
  src/shared/components/Flex/index.tsx
  src/shared/components/Footer/index.tsx
  src/shared/hooks/useDraggable.ts
  src/shared/libs/next-auth/auth-provider.tsx
  src/shared/styles/globals.css
  src/shared/types/next-auth.d.ts
  src/shared/types/profile.ts
  src/shared/utils/authOptions.ts
  src/shared/utils/schema.ts
  yarn.lock
Labels: 🍠 deploy

#29 [CRAB-12] 모바일 화면 navbar 수정
  src/features/main/SecondBanner/index.tsx
  src/features/main/components/FifthBanner/index.tsx
  src/features/main/components/FourthBanner/index.tsx
  src/features/main/components/MainBanner/index.tsx
  src/features/main/components/MainCard/index.tsx
  src/features/main/components/MenuItem/index.tsx
  src/features/main/components/ScholarshipCard/index.tsx
  src/features/main/components/ThirdBanner/index.tsx
  src/features/main/components/UserMenu/index.tsx
Labels: ✨ feature

#31 [CRAB-13] 권한별 tab-bar ui 수정
  src/app/academy/(workspace)/[id]/layout.tsx
  src/app/academy/(workspace)/layout.tsx
  src/features/academy/(workspace)/components/workspace-tab.tsx
  src/features/academy/components/tab-button.tsx
  src/shared/types/acadmy.ts
Labels: ✨ feature

#33 [CRAB-15] sonner 설치, fetch 설정
  eslint/default.js
  package.json
  src/app/academy/(academy)/my/page.tsx
  src/app/layout.tsx
  src/features/main/components/UserMenu/index.tsx
  src/shared/styles/reset.css
  yarn.lock
Labels: ✨ feature

#36 [CRAB-16] 챌린지 생성 구현
  src/app/academy/(workspace)/[id]/dashboard/layout.tsx
  src/app/academy/(workspace)/[id]/layout.tsx
  src/app/layout.tsx
  src/features/academy/(workspace)/api/get-academy-profile.ts
  src/features/academy/(workspace)/api/post-academy-challenges.ts
  src/features/academy/(workspace)/components/dashboard/ChallengeModal/First.tsx
  src/features/academy/(workspace)/components/dashboard/ChallengeModal/Second.tsx
  src/features/academy/(workspace)/components/dashboard/ChallengeModal/Third.tsx
  src/features/academy/(workspace)/components/dashboard/ChallengeModal/index.tsx
  src/features/academy/(workspace)/components/dashboard/Sidebar/index.tsx
  src/features/academy/(workspace)/components/dashboard/Students/index.tsx
  src/features/academy/(workspace)/components/error/index.tsx
  src/features/academy/(workspace)/hooks/challenges/use-create-challenges.ts
  src/features/academy/(workspace)/hooks/challenges/use-get-students.ts
  src/features/academy/(workspace)/hooks/use-challenge-modal.ts
  src/features/academy/(workspace)/hooks/use-image.ts
  src/features/main/components/LoginModal/index.tsx
  src/shared/components/Input/index.tsx
  src/shared/components/ProgressBar/index.tsx
  src/shared/components/SelectDropdown/index.tsx
  src/shared/components/Textarea/index.tsx
  src/shared/constants/challenge-cataegrories.ts
  src/shared/hooks/images/use-get-presigned-url.ts
  src/shared/types/acadmy.ts
  src/shared/types/images.ts
  src/shared/utils/schema.ts
Labels: ✨ feature

#38 [CRAB-17] SSR dehydrate 무한스크롤 구현, 반응형 에러 수정, Skeleton UI 구현
  eslint/tailwindcss.js
  package.json
  src/app/academy/(academy)/alert/page.tsx
  src/app/academy/(academy)/my/components/academy-list/index.tsx
  src/app/academy/(academy)/my/page.tsx
  src/app/layout.tsx
  src/features/academy/alert/components/ListRow.tsx
  src/features/academy/my/components/Sidebar/side-bar.tsx
  src/shared/apis/academy.ts
  src/shared/components/Flex/index.tsx
  src/shared/components/Skeleton/Skeleton.tsx
  src/shared/constants/query-keys.ts
  src/shared/hooks/academy/useGetInfiniteAcademyList.ts
  src/shared/types/acadmy.ts
  tailwind.config.ts
  yarn.lock
Labels: ✨ feature

#42 [CRAB-20] dashboard UI
  src/app/academy/(workspace)/[id]/dashboard/layout.tsx
  src/app/academy/(workspace)/[id]/dashboard/page.tsx
  src/features/academy/(workspace)/components/challenge-card/index.tsx
  src/features/academy/(workspace)/components/challenge-list/index.tsx
  src/features/academy/(workspace)/components/dashboard/Sidebar/index.tsx
  src/features/academy/(workspace)/components/dashboard/academy-title/index.tsx
  src/features/academy/(workspace)/components/dashboard/best-challenge-table/index.tsx
  src/features/academy/(workspace)/components/dashboard/chart-view/index.tsx
  src/features/academy/(workspace)/components/my-challenge-card/index.tsx
  src/features/academy/(workspace)/components/my-challenge-list/index.tsx
  src/features/academy/(workspace)/utils/challengeState.ts
  src/shared/enums/challenge.ts
  src/shared/hooks/use-draggable.ts
  src/shared/types/acadmy.ts
  src/shared/utils/date.ts
Labels: ✨ feature

#44 [CRAB-19] 학원 등록하기 API 연결, 학원 생성 버그 수정
  eslint/react.js
  src/features/space/enroll/components/form.tsx
  src/shared/apis/academy.ts
  src/shared/components/AddressSearch/address-search.tsx
Labels: ✨ feature

#46 [CRAB-22] (원장) 학원 스페이스에 가입 신청한 유저 리스트 조회, 학원 스페이스, 신청 리스트 화면 구현
  src/app/academy/(academy)/my/page.tsx
  src/app/academy/(workspace)/[id]/application/components/ApplicationList/index.tsx
  src/app/academy/(workspace)/[id]/application/page.tsx
  src/app/academy/(workspace)/[id]/setting/components/setting-list/index.tsx
  src/app/academy/(workspace)/[id]/setting/page.tsx
  src/shared/apis/challenge.ts
  src/shared/constants/query-keys.ts
  src/shared/enums/academy.ts
  src/shared/hooks/academy/useGetInfiniteApplicationList.ts
  src/shared/types/acadmy.ts
Labels: ✨ feature

#48 [CRAB-21] 챌린지 상세 페이지
  src/app/academy/(workspace)/[id]/challenge/[challengeId]/page.tsx
  src/app/academy/(workspace)/[id]/challenge/[challengeId]/student/[studentId]/page.tsx
  src/app/academy/(workspace)/[id]/challenge/components/StudentChallengeContents/index.tsx
  src/app/academy/(workspace)/[id]/challenge/page.tsx
  src/features/academy/(workspace)/components/challenge-card/index.tsx
  src/features/academy/(workspace)/components/challenge-list/index.tsx
  src/features/academy/(workspace)/components/challenge/challenge-detail/index.tsx
  src/features/academy/(workspace)/components/challenge/challenge-student-list/index.tsx
  src/features/academy/(workspace)/components/state-label/index.tsx
  src/features/academy/(workspace)/utils/challengeState.ts
  src/shared/apis/challenge.ts
  src/shared/constants/query-keys.ts
  src/shared/enums/challenge.ts
  src/shared/hooks/challenge/useGetInfiniteStudentChallengeContents.ts
  src/shared/hooks/challenge/useGetInfiniteStudentChallengeProgressList.ts
  src/shared/types/acadmy.ts
Labels: ✨ feature

#50 [CRAB-23] (원장) 학생 리스트 조회, 학생 리스트 화면 구현
  src/app/academy/(workspace)/[id]/members/detail/components/StudentDetailList/index.tsx
  src/app/academy/(workspace)/[id]/members/detail/page.tsx
  src/app/academy/(workspace)/[id]/setting/components/setting-list/index.tsx
  src/features/academy/(workspace)/api/post-academy-challenges.ts
  src/features/main/components/RegisterModal/index.tsx
  src/shared/apis/academy.ts
  src/shared/apis/challenge.ts
  src/shared/constants/query-keys.ts
  src/shared/hooks/academy/useGetInfiniteAcademyMemberDetailList.ts
  src/shared/hooks/images/use-get-presigned-url.ts
  src/shared/libs/axios-instance.ts
  src/shared/types/acadmy.ts
  src/shared/utils/authOptions.ts
Labels: ✨ feature

#54 [CRAB-25] (원장, 강사) 학원 전체, 학생 기본 프로필 리스트 조회
  src/app/academy/(workspace)/[id]/members/student/components/StudentDetailList/index.tsx
  src/app/academy/(workspace)/[id]/members/student/page.tsx
  src/app/academy/(workspace)/[id]/setting/components/setting-list/index.tsx
  src/shared/apis/challenge.ts
  src/shared/constants/query-keys.ts
  src/shared/hooks/academy/useGetInfiniteAcademyStudentList.ts
  src/shared/types/acadmy.ts
Labels: ✨ feature

#56 [Deploy] 2024년 10월 26일 Daily Deploy
  src/app/academy/(workspace)/[id]/members/detail/components/StudentDetailList/index.tsx
  src/app/academy/(workspace)/[id]/members/detail/page.tsx
  src/app/academy/(workspace)/[id]/members/instructor/components/InstructorDetailList/index.tsx
  src/app/academy/(workspace)/[id]/members/instructor/page.tsx
  src/app/academy/(workspace)/[id]/members/student/components/StudentDetailList/index.tsx
  src/app/academy/(workspace)/[id]/members/student/page.tsx
  src/app/academy/(workspace)/[id]/setting/components/setting-list/index.tsx
  src/features/academy/(workspace)/api/post-academy-challenges.ts
  src/features/main/components/RegisterModal/index.tsx
  src/shared/apis/academy.ts
  src/shared/apis/challenge.ts
  src/shared/constants/query-keys.ts
  src/shared/hooks/academy/useGetInfiniteAcademyInstructorList.ts
  src/shared/hooks/academy/useGetInfiniteAcademyMemberDetailList.ts
  src/shared/hooks/academy/useGetInfiniteAcademyStudentList.ts
  src/shared/hooks/images/use-get-presigned-url.ts
  src/shared/libs/axios-instance.ts
  src/shared/types/acadmy.ts
  src/shared/utils/authOptions.ts
Labels: ✨ feature

#58 [CRAB-27] 학원 스페이스 탈퇴 기능 구현, 서버 필드 변경 사항 반영
  src/app/academy/(workspace)/[id]/members/student/components/StudentDetailList/index.tsx
  src/app/academy/(workspace)/[id]/setting/components/revoke-button/index.tsx
  src/app/academy/(workspace)/[id]/setting/components/setting-list/index.tsx
  src/features/space/enroll/components/form.tsx
  src/shared/apis/academy.ts
  src/shared/apis/dto/response.ts
  src/shared/apis/fetch-data.ts
  src/shared/constants/api-error-message.ts
  src/shared/types/acadmy.ts
Labels: ✨ feature

#59 [CRAB-26] 학생/강사/원장 챌린지 보드 수정 및 상세 챌린지 보기
  src/app/academy/(workspace)/[id]/challenge/[challengeId]/page.tsx
  src/app/academy/(workspace)/[id]/challenge/[challengeId]/student/[studentId]/page.tsx
  src/app/academy/(workspace)/[id]/challenge/components/ChallengeDetail/index.tsx
  src/app/academy/(workspace)/[id]/challenge/components/MyChallengeContentForm/index.tsx
  src/app/academy/(workspace)/[id]/challenge/components/StudentChallengeContent/index.tsx
  src/app/academy/(workspace)/[id]/challenge/components/StudentChallengeContents/index.tsx
  src/app/academy/(workspace)/[id]/challenge/components/StudentChallengeDetail/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/layout.tsx
  src/app/academy/(workspace)/[id]/dashboard/page.tsx
  src/app/academy/(workspace)/[id]/layout.tsx
  src/app/academy/(workspace)/[id]/my-challenge/[studentId]/page.tsx
  src/app/academy/(workspace)/[id]/my-challenge/challenge/[studentChallengeId]/page.tsx
  src/app/academy/(workspace)/[id]/setting/page.tsx
  src/features/academy/(workspace)/api/get-academy-profile.ts
  src/features/academy/(workspace)/api/post-academy-challenges.ts
  src/features/academy/(workspace)/components/challenge-card/index.tsx
  src/features/academy/(workspace)/components/challenge-list/index.tsx
  src/features/academy/(workspace)/components/challenge/challenge-student-list/index.tsx
  src/features/academy/(workspace)/components/dashboard/ChallengeModal/Third.tsx
  src/features/academy/(workspace)/components/dashboard/ChallengeModal/index.tsx
  src/features/academy/(workspace)/components/dashboard/Students/index.tsx
  src/features/academy/(workspace)/components/dashboard/academy-title/index.tsx
  src/features/academy/(workspace)/components/my-challenge-card/index.tsx
  src/features/academy/(workspace)/components/workspace-tab.tsx
  src/features/academy/(workspace)/hooks/challenges/use-create-challenges.ts
  src/features/academy/(workspace)/hooks/challenges/use-get-students.ts
  src/features/academy/(workspace)/utils/challengeState.ts
  src/features/main/components/RegisterModal/index.tsx
  src/shared/apis/challenge.ts
  src/shared/components/Avatar/index.tsx
  src/shared/components/Footer/index.tsx
  src/shared/hooks/challenge/useCreateChallengeContent.ts
  src/shared/hooks/challenge/useGetInfiniteStudentChallengeContents.ts
  src/shared/hooks/images/use-get-presigned-url.ts
  src/shared/libs/axios-instance.ts
  src/shared/types/acadmy.ts
  src/shared/utils/academyRole.ts
  src/shared/utils/authOptions.ts
Labels: ✨ feature

#60 [Deploy] 2024년 10월 28일 Daily Deploy
  src/app/academy/(workspace)/[id]/challenge/[challengeId]/page.tsx
  src/app/academy/(workspace)/[id]/challenge/[challengeId]/student/[studentId]/page.tsx
  src/app/academy/(workspace)/[id]/challenge/components/ChallengeDetail/index.tsx
  src/app/academy/(workspace)/[id]/challenge/components/MyChallengeContentForm/index.tsx
  src/app/academy/(workspace)/[id]/challenge/components/StudentChallengeContent/index.tsx
  src/app/academy/(workspace)/[id]/challenge/components/StudentChallengeContents/index.tsx
  src/app/academy/(workspace)/[id]/challenge/components/StudentChallengeDetail/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/layout.tsx
  src/app/academy/(workspace)/[id]/dashboard/page.tsx
  src/app/academy/(workspace)/[id]/layout.tsx
  src/app/academy/(workspace)/[id]/members/student/components/StudentDetailList/index.tsx
  src/app/academy/(workspace)/[id]/my-challenge/[studentId]/page.tsx
  src/app/academy/(workspace)/[id]/my-challenge/challenge/[studentChallengeId]/page.tsx
  src/app/academy/(workspace)/[id]/setting/components/revoke-button/index.tsx
  src/app/academy/(workspace)/[id]/setting/components/setting-list/index.tsx
  src/app/academy/(workspace)/[id]/setting/page.tsx
  src/features/academy/(workspace)/api/get-academy-profile.ts
  src/features/academy/(workspace)/api/post-academy-challenges.ts
  src/features/academy/(workspace)/components/challenge-card/index.tsx
  src/features/academy/(workspace)/components/challenge-list/index.tsx
  src/features/academy/(workspace)/components/challenge/challenge-student-list/index.tsx
  src/features/academy/(workspace)/components/dashboard/ChallengeModal/Third.tsx
  src/features/academy/(workspace)/components/dashboard/ChallengeModal/index.tsx
  src/features/academy/(workspace)/components/dashboard/Students/index.tsx
  src/features/academy/(workspace)/components/dashboard/academy-title/index.tsx
  src/features/academy/(workspace)/components/my-challenge-card/index.tsx
  src/features/academy/(workspace)/components/workspace-tab.tsx
  src/features/academy/(workspace)/hooks/challenges/use-create-challenges.ts
  src/features/academy/(workspace)/hooks/challenges/use-get-students.ts
  src/features/academy/(workspace)/utils/challengeState.ts
  src/features/main/components/RegisterModal/index.tsx
  src/features/space/enroll/components/form.tsx
  src/shared/apis/academy.ts
  src/shared/apis/challenge.ts
  src/shared/apis/dto/response.ts
  src/shared/apis/fetch-data.ts
  src/shared/components/Avatar/index.tsx
  src/shared/components/Footer/index.tsx
  src/shared/constants/api-error-message.ts
  src/shared/hooks/challenge/useCreateChallengeContent.ts
  src/shared/hooks/challenge/useGetInfiniteStudentChallengeContents.ts
  src/shared/hooks/images/use-get-presigned-url.ts
  src/shared/libs/axios-instance.ts
  src/shared/types/acadmy.ts
  src/shared/utils/academyRole.ts
  src/shared/utils/authOptions.ts
Labels: 🍠 deploy

#63 [CRAB-29] 가입 코드 페이지 / 기능 구현
  src/app/academy/(workspace)/[id]/invitation/components/Invitation/index.tsx
  src/app/academy/(workspace)/[id]/invitation/page.tsx
  src/app/academy/(workspace)/[id]/setting/components/setting-list/index.tsx
  src/shared/apis/invitation.ts
  src/shared/constants/query-keys.ts
  src/shared/types/invitation.ts
Labels: ✨ feature

#64 [CRAB-28] 챌린지 승인/반려처리 및 학생 대시보드 공개 챌린지
  src/app/academy/(workspace)/[id]/challenge/[challengeId]/student/[studentId]/page.tsx
  src/app/academy/(workspace)/[id]/challenge/components/ChallengeDetail/index.tsx
  src/app/academy/(workspace)/[id]/challenge/components/MyChallengeContentForm/index.tsx
  src/app/academy/(workspace)/[id]/challenge/components/StudentChallengeContent/index.tsx
  src/app/academy/(workspace)/[id]/challenge/components/StudentChallengeDetail/index.tsx
  src/app/academy/(workspace)/[id]/challenge/components/StudentTableContent/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/BestStudentTableContent/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/page.tsx
  src/app/academy/(workspace)/[id]/market/@modal/(.)[...slug]/page.tsx
  src/app/academy/(workspace)/[id]/market/@modal/default.tsx
  src/app/academy/(workspace)/[id]/market/[...slug]/page.tsx
  src/app/academy/(workspace)/[id]/market/components/ChallengeCard/index.tsx
  src/app/academy/(workspace)/[id]/market/components/ChallengeTab/index.tsx
  src/app/academy/(workspace)/[id]/market/components/ModalDetail/index.tsx
  src/app/academy/(workspace)/[id]/market/components/PublicChallengeLists/index.tsx
  src/app/academy/(workspace)/[id]/market/layout.tsx
  src/app/academy/(workspace)/[id]/market/page.tsx
  src/app/academy/(workspace)/[id]/my-challenge/challenge/[studentChallengeId]/page.tsx
  src/features/academy/(workspace)/api/post-academy-challenges.ts
  src/features/academy/(workspace)/components/challenge/challenge-student-list/index.tsx
  src/features/academy/(workspace)/components/dashboard/best-challenge-table/index.tsx
  src/features/academy/(workspace)/components/dashboard/chart-view/index.tsx
  src/features/academy/(workspace)/components/workspace-tab.tsx
  src/features/academy/(workspace)/hooks/challenges/use-create-challenges.ts
  src/features/academy/(workspace)/hooks/use-image.ts
  src/features/academy/(workspace)/utils/challengeState.ts
  src/shared/apis/academy.ts
  src/shared/apis/challenge.ts
  src/shared/apis/market.ts
  src/shared/constants/query-keys.ts
  src/shared/enums/challenge.ts
  src/shared/hooks/challenge/useApprovalChallenge.ts
  src/shared/hooks/challenge/useCreateChallengeContent.ts
  src/shared/hooks/market/useApplyChallenge.ts
  src/shared/hooks/market/useGetInfinitePublicChallenge.ts
  src/shared/types/acadmy.ts
  src/shared/types/market.ts
Labels: ✨ feature

#65 [Deploy] 2024년 10월 29일 Daily Deploy
  src/app/academy/(workspace)/[id]/challenge/[challengeId]/student/[studentId]/page.tsx
  src/app/academy/(workspace)/[id]/challenge/components/ChallengeDetail/index.tsx
  src/app/academy/(workspace)/[id]/challenge/components/MyChallengeContentForm/index.tsx
  src/app/academy/(workspace)/[id]/challenge/components/StudentChallengeContent/index.tsx
  src/app/academy/(workspace)/[id]/challenge/components/StudentChallengeDetail/index.tsx
  src/app/academy/(workspace)/[id]/challenge/components/StudentTableContent/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/BestStudentTableContent/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/page.tsx
  src/app/academy/(workspace)/[id]/invitation/components/Invitation/index.tsx
  src/app/academy/(workspace)/[id]/invitation/page.tsx
  src/app/academy/(workspace)/[id]/market/@modal/(.)[...slug]/page.tsx
  src/app/academy/(workspace)/[id]/market/@modal/default.tsx
  src/app/academy/(workspace)/[id]/market/[...slug]/page.tsx
  src/app/academy/(workspace)/[id]/market/components/ChallengeCard/index.tsx
  src/app/academy/(workspace)/[id]/market/components/ChallengeTab/index.tsx
  src/app/academy/(workspace)/[id]/market/components/ModalDetail/index.tsx
  src/app/academy/(workspace)/[id]/market/components/PublicChallengeLists/index.tsx
  src/app/academy/(workspace)/[id]/market/layout.tsx
  src/app/academy/(workspace)/[id]/market/page.tsx
  src/app/academy/(workspace)/[id]/my-challenge/challenge/[studentChallengeId]/page.tsx
  src/app/academy/(workspace)/[id]/setting/components/setting-list/index.tsx
  src/features/academy/(workspace)/api/post-academy-challenges.ts
  src/features/academy/(workspace)/components/challenge/challenge-student-list/index.tsx
  src/features/academy/(workspace)/components/dashboard/best-challenge-table/index.tsx
  src/features/academy/(workspace)/components/dashboard/chart-view/index.tsx
  src/features/academy/(workspace)/components/workspace-tab.tsx
  src/features/academy/(workspace)/hooks/challenges/use-create-challenges.ts
  src/features/academy/(workspace)/hooks/use-image.ts
  src/features/academy/(workspace)/utils/challengeState.ts
  src/shared/apis/academy.ts
  src/shared/apis/challenge.ts
  src/shared/apis/invitation.ts
  src/shared/apis/market.ts
  src/shared/constants/query-keys.ts
  src/shared/enums/challenge.ts
  src/shared/hooks/challenge/useApprovalChallenge.ts
  src/shared/hooks/challenge/useCreateChallengeContent.ts
  src/shared/hooks/market/useApplyChallenge.ts
  src/shared/hooks/market/useGetInfinitePublicChallenge.ts
  src/shared/types/acadmy.ts
  src/shared/types/invitation.ts
  src/shared/types/market.ts
Labels: 🍠 deploy

#68 [CRAB-30] 대시보드 통계 연결 & 학생 대시보드 연결
  src/app/academy/(workspace)/[id]/challenge/components/ChallengeDetail/index.tsx
  src/app/academy/(workspace)/[id]/challenge/components/StudentChallengeContent/index.tsx
  src/app/academy/(workspace)/[id]/challenge/components/StudentTableContent/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/AllChallengeContents/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/BarChart/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/DashboardCard/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/DashboardChallengeTable/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/DonutChart/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/layout.tsx
  src/app/academy/(workspace)/[id]/dashboard/page.tsx
  src/app/academy/(workspace)/[id]/market/components/ChallengeCard/index.tsx
  src/app/academy/(workspace)/[id]/market/components/ModalDetail/index.tsx
  src/features/academy/(workspace)/components/challenge-card/index.tsx
  src/features/academy/(workspace)/components/challenge/challenge-student-list/index.tsx
  src/features/academy/(workspace)/components/dashboard/academy-title/index.tsx
  src/features/academy/(workspace)/components/dashboard/best-challenge-table/index.tsx
  src/features/academy/(workspace)/components/dashboard/chart-view/index.tsx
  src/features/academy/(workspace)/components/my-challenge-card/index.tsx
  src/features/main/components/UserMenu/index.tsx
  src/shared/apis/academy.ts
  src/shared/apis/challenge.ts
  src/shared/constants/query-keys.ts
  src/shared/hooks/challenge/useGetInfiniteAllChallengeContents.ts
  src/shared/types/acadmy.ts
Labels: ✨ feature

#69 [Deploy] 2024년 10월 29일 Daily Deploy
  src/app/academy/(workspace)/[id]/challenge/components/ChallengeDetail/index.tsx
  src/app/academy/(workspace)/[id]/challenge/components/StudentChallengeContent/index.tsx
  src/app/academy/(workspace)/[id]/challenge/components/StudentTableContent/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/AllChallengeContents/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/BarChart/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/DashboardCard/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/DashboardChallengeTable/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/DonutChart/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/layout.tsx
  src/app/academy/(workspace)/[id]/dashboard/page.tsx
  src/app/academy/(workspace)/[id]/market/components/ChallengeCard/index.tsx
  src/app/academy/(workspace)/[id]/market/components/ModalDetail/index.tsx
  src/features/academy/(workspace)/components/challenge-card/index.tsx
  src/features/academy/(workspace)/components/challenge/challenge-student-list/index.tsx
  src/features/academy/(workspace)/components/dashboard/academy-title/index.tsx
  src/features/academy/(workspace)/components/dashboard/best-challenge-table/index.tsx
  src/features/academy/(workspace)/components/dashboard/chart-view/index.tsx
  src/features/academy/(workspace)/components/my-challenge-card/index.tsx
  src/features/main/components/UserMenu/index.tsx
  src/shared/apis/academy.ts
  src/shared/apis/challenge.ts
  src/shared/constants/query-keys.ts
  src/shared/hooks/challenge/useGetInfiniteAllChallengeContents.ts
  src/shared/types/acadmy.ts
Labels: 🍠 deploy
