Repository crabit-official/Crabit-FE2, pull requests merged in 2024-12, with the labels that each got.

#196 [CRAB-82] 사파리 글씨 두께 해결
  src/shared/styles/globals.css
Labels: 🐛 bug

#198 [CRAB-83] 설정페이지 수정
  src/app/academy/(workspace)/[id]/dashboard/components/BestStudentTableContent/index.tsx
  src/app/academy/(workspace)/[id]/setting/components/AcademyProfileForm/index.tsx
  src/app/academy/(workspace)/[id]/setting/components/SettingBar/index.tsx
  src/app/academy/(workspace)/[id]/setting/components/SettingInfo/index.tsx
  src/app/academy/(workspace)/[id]/setting/layout.tsx
  src/app/academy/(workspace)/[id]/setting/management/instructor/components/InstructorDetail/index.tsx
  src/app/academy/(workspace)/[id]/setting/management/student/components/ChallengeStatisticsTable/index.tsx
  src/app/academy/(workspace)/[id]/setting/management/student/components/MemberDetail/index.tsx
  src/app/academy/(workspace)/[id]/setting/page.tsx
  src/features/academy/(workspace)/components/dashboard/best-challenge-table/index.tsx
  src/shared/constants/student-statistics.ts
Labels: ✨ feature

#199 [Deploy] 2024년 12월 1일 Daily Deploy
  src/app/academy/(workspace)/[id]/dashboard/components/BestStudentTableContent/index.tsx
  src/app/academy/(workspace)/[id]/setting/components/AcademyProfileForm/index.tsx
  src/app/academy/(workspace)/[id]/setting/components/SettingBar/index.tsx
  src/app/academy/(workspace)/[id]/setting/components/SettingInfo/index.tsx
  src/app/academy/(workspace)/[id]/setting/layout.tsx
  src/app/academy/(workspace)/[id]/setting/management/instructor/components/InstructorDetail/index.tsx
  src/app/academy/(workspace)/[id]/setting/management/student/components/ChallengeStatisticsTable/index.tsx
  src/app/academy/(workspace)/[id]/setting/management/student/components/MemberDetail/index.tsx
  src/app/academy/(workspace)/[id]/setting/page.tsx
  src/features/academy/(workspace)/components/dashboard/best-challenge-table/index.tsx
  src/shared/constants/student-statistics.ts
  src/shared/styles/globals.css
Labels: 🍠 deploy

#203 [CRAB-85] 설정 페이지 가입 코드 관련 페이지
  src/app/academy/(workspace)/[id]/invitation/page.tsx
  src/app/academy/(workspace)/[id]/setting/components/SettingBar/index.tsx
  src/app/academy/(workspace)/[id]/setting/management/invitation/components/Invitation/index.tsx
  src/app/academy/(workspace)/[id]/setting/management/invitation/page.tsx
Labels: ✨ feature

#204 [Deploy] 2024년 12월 1일 Daily Deploy
  src/app/academy/(academy)/layout.tsx
  src/app/academy/(workspace)/[id]/invitation/page.tsx
  src/app/academy/(workspace)/[id]/setting/components/SettingBar/index.tsx
  src/app/academy/(workspace)/[id]/setting/management/invitation/components/Invitation/index.tsx
  src/app/academy/(workspace)/[id]/setting/management/invitation/page.tsx
  src/app/layout.tsx
  src/app/not-found.tsx
Labels: 🍠 deploy

#206 [CRAB-86] navbar 변경
  src/app/academy/(academy)/alert/page.tsx
  src/app/academy/(academy)/layout.tsx
  src/app/academy/(academy)/setting/page.tsx
  src/app/my/academy/page.tsx
  src/app/my/components/academy-list/index.tsx
  src/app/my/components/invitation-modal/components/Tab.tsx
  src/app/my/components/invitation-modal/index.tsx
  src/app/my/hooks/use-invitation-modal.ts
  src/app/my/layout.tsx
  src/features/main/components/AcademyMenu/index.tsx
  src/features/main/components/AcademyProfileMenu/index.tsx
  src/features/main/components/MenuItem/index.tsx
  src/features/main/components/Navbar/index.tsx
  src/features/main/components/UserMenu/index.tsx
  src/shared/styles/globals.css
Labels: ✨ feature

#207 [Deploy] 2024년 12월 1일 Daily Deploy
  src/app/academy/(academy)/alert/page.tsx
  src/app/academy/(academy)/layout.tsx
  src/app/academy/(academy)/setting/page.tsx
  src/app/my/academy/page.tsx
  src/app/my/components/academy-list/index.tsx
  src/app/my/components/invitation-modal/components/Tab.tsx
  src/app/my/components/invitation-modal/index.tsx
  src/app/my/hooks/use-invitation-modal.ts
  src/app/my/layout.tsx
  src/features/main/components/AcademyMenu/index.tsx
  src/features/main/components/AcademyProfileMenu/index.tsx
  src/features/main/components/MenuItem/index.tsx
  src/features/main/components/Navbar/index.tsx
  src/features/main/components/UserMenu/index.tsx
  src/shared/styles/globals.css
Labels: 🍠 deploy

#211 [CRAB-89] 로그인 / 비로그인시 비밀번호 변경 관련, 서버 변경 및 추가사항 반영.
  src/app/api/auth/password/route.ts
  src/app/layout.tsx
  src/app/profile/components/EmailForm/index.tsx
  src/app/profile/components/PasswordForm/index.tsx
  src/features/main/components/LoginModal/index.tsx
  src/features/main/components/PasswordChangeModal/index.tsx
  src/features/main/hooks/use-password-change-modal.ts
  src/shared/apis/auth.ts
  src/shared/apis/profile.ts
  src/shared/components/Input/index.tsx
  src/shared/components/Modal/index.tsx
  src/shared/hooks/auth/queries/usePasswordChange.ts
  src/shared/hooks/email/useVerifyCode.ts
  src/shared/types/auth.ts
  src/shared/utils/schema.ts
Labels: ✨ feature

#214 [Deploy] 2024년 12월 3일 Daily Deploy
  src/app/academy/(workspace)/[id]/dashboard/components/MenuItem/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/Menubar/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/page.tsx
  src/app/academy/(workspace)/[id]/public-challenge/components/PublicCardList/index.tsx
  src/app/academy/(workspace)/[id]/public-challenge/page.tsx
  src/features/main/components/AcademyMenu/index.tsx
  src/features/main/components/AcademyProfileMenu/index.tsx
  src/features/main/components/UserMenu/index.tsx
Labels: ✨ feature

#216 [CRAB-90] 설정 페이지 변경
  src/app/academy/(workspace)/[id]/setting/components/AcademyProfileForm/index.tsx
  src/app/academy/(workspace)/[id]/setting/components/SettingBar/index.tsx
  src/app/academy/(workspace)/[id]/setting/management/instructor/components/InstructorDetail/index.tsx
  src/app/academy/(workspace)/[id]/setting/management/invitation/components/Invitation/index.tsx
  src/app/academy/(workspace)/[id]/setting/management/invitation/page.tsx
  src/features/main/components/AcademyProfileMenu/index.tsx
  src/shared/hooks/academy/useManageAcademy.ts
  src/shared/utils/academyRole.ts
Labels: ✨ feature

#218 [CRAB-91] 유저 역할 명칭 변경 (화면) 및 기관 생성하기 수정
  src/app/academy/(workspace)/[id]/dashboard/page.tsx
  src/app/academy/(workspace)/[id]/members/detail/components/StudentDetailList/index.tsx
  src/app/academy/(workspace)/[id]/members/detail/page.tsx
  src/app/academy/(workspace)/[id]/members/instructor/components/InstructorDetailList/index.tsx
  src/app/academy/(workspace)/[id]/members/instructor/page.tsx
  src/app/academy/(workspace)/[id]/members/student/components/StudentDetailList/index.tsx
  src/app/academy/(workspace)/[id]/members/student/page.tsx
  src/app/academy/(workspace)/[id]/setting/components/revoke-button/index.tsx
  src/app/academy/(workspace)/[id]/setting/components/setting-list/index.tsx
  src/app/my/components/academy-list/index.tsx
  src/app/my/components/invitation-modal/index.tsx
  src/features/main/components/UserMenu/index.tsx
  src/features/space/enroll/components/form.tsx
  src/shared/components/Modal/index.tsx
  src/shared/enums/academy.ts
  src/shared/types/acadmy.ts
Labels: ✨ feature

#229 [CRAB-94] 기관정보 수정 후 navbar에 수정정보 반영
  src/app/academy/(workspace)/[id]/setting/components/SettingInfo/index.tsx
  src/app/academy/(workspace)/[id]/setting/layout.tsx
  src/app/academy/(workspace)/[id]/setting/management/institution/components/EditForm/index.tsx
  src/shared/hooks/academy/useGetInfiniteAcademyList.ts
Labels: ✨ feature

#230 [CRAB-93] 마켓 챌린지 배포 오류 수정
  src/app/academy/(workspace)/[id]/dashboard/create/components/Last.tsx
  src/app/academy/(workspace)/[id]/market/components/ChallengeDetail/index.tsx
  src/app/academy/(workspace)/[id]/market/components/ModalDetail/index.tsx
  src/app/academy/(workspace)/[id]/market/components/Release/First.tsx
  src/app/academy/(workspace)/[id]/market/components/Release/Second.tsx
  src/shared/components/Footer/index.tsx
  src/shared/components/Input/index.tsx
  src/shared/components/SelectDropdown/index.tsx
  src/shared/components/Textarea/index.tsx
  src/shared/utils/schema.ts
  tailwind.config.ts
Labels: 🐛 bug, ✨ feature

#232 [CRAB-95] 대시보드 페이지 수정
  package.json
  public/mockServiceWorker.js
  src/app/academy/(workspace)/[id]/dashboard/[challengeId]/page.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/(principal)/ChallengeDetail/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/(student)/CreateChallengeForm/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/(student)/MyChallengeDetail/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/ChallengeDetail/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/ChallengeStatistics/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/StudentCard/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/StudentCardList/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/page.tsx
  src/app/academy/(workspace)/[id]/setting/management/instructor/components/InstructorDetail/index.tsx
  src/app/academy/(workspace)/[id]/setting/management/student/components/MemberDetail/index.tsx
  src/app/layout.tsx
  src/features/main/components/LoginModal/index.tsx
  src/features/main/components/MarketingModal/index.tsx
  src/features/main/components/RegisterModal/index.tsx
  src/features/main/components/ServiceModal/index.tsx
  src/features/main/components/TermModal/index.tsx
  src/features/main/hooks/use-marketing-modal.ts
  src/features/main/hooks/use-service-modal.ts
  src/features/main/hooks/use-term-modal.ts
  src/shared/components/CheckBox/index.tsx
  src/shared/components/Modal/index.tsx
  src/shared/components/SmallModal/index.tsx
  src/shared/hooks/usePortal.ts
  src/shared/types/acadmy.ts
  yarn.lock
Labels: ✨ feature

#231 [CRAB-96] 1차 출시 관련 QA 수정
  src/app/academy/(workspace)/[id]/dashboard/components/(student)/MyChallengeDetail/index.tsx
  src/features/main/components/ServiceModal/index.tsx
Labels: ✨ feature

#238 [CRAB-98] 챌린지 수정
  src/app/academy/(workspace)/[id]/dashboard/components/(principal)/ChallengeDetail/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/(principal)/ChallengeEditForm/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/ChallengeDetail/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/ChallengeStatistics/index.tsx
  src/app/api/challenge/detail/route.ts
  src/app/api/challenge/route.ts
  src/shared/apis/challenge.ts
  src/shared/components/FallbackMessage/index.tsx
  src/shared/constants/query-keys.ts
  src/shared/hooks/challenge/useEditChallenge.ts
  src/shared/hooks/challenge/useGetChallengeDetail.ts
  src/shared/types/acadmy.ts
  src/shared/utils/schema.ts
Labels: ✨ feature

#239 [CRAB-99] 반응형 수정
  public/images/logo_nsc.webp
  src/app/academy/(workspace)/[id]/market/components/ModalContent/index.tsx
  src/app/layout.tsx
  src/features/main/components/ThirdBanner/index.tsx
Labels: ✨ feature

#240 [Deploy] 2024년 12월 6일 Daily Deploy
  public/images/logo_nsc.webp
  src/app/academy/(workspace)/[id]/dashboard/components/(principal)/ChallengeDetail/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/(principal)/ChallengeEditForm/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/ChallengeDetail/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/ChallengeStatistics/index.tsx
  src/app/academy/(workspace)/[id]/market/components/ModalContent/index.tsx
  src/app/api/challenge/detail/route.ts
  src/app/api/challenge/route.ts
  src/app/layout.tsx
  src/features/main/components/ThirdBanner/index.tsx
  src/shared/apis/challenge.ts
  src/shared/components/FallbackMessage/index.tsx
  src/shared/constants/query-keys.ts
  src/shared/hooks/challenge/useEditChallenge.ts
  src/shared/hooks/challenge/useGetChallengeDetail.ts
  src/shared/types/acadmy.ts
  src/shared/utils/schema.ts
Labels: 🍠 deploy

#243 [Deploy] 2024년 12월 7일 Daily Deploy
  src/app/academy/(workspace)/[id]/dashboard/components/StudentChallengeContent/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/StudentChallengeContents/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/create/components/Last.tsx
  src/app/academy/(workspace)/[id]/feed/components/ChallengeDetail/index.tsx
  src/app/academy/(workspace)/[id]/feed/components/Comment/index.tsx
  src/app/academy/(workspace)/[id]/feed/components/CommentForm/index.tsx
  src/app/academy/(workspace)/[id]/market/components/ModalContent/index.tsx
  src/shared/utils/timeForToday.ts
Labels: 🍠 deploy

#245 [CRAB-101] 날짜 적용 오류 수정
  src/app/academy/(workspace)/[id]/feed/components/ChallengeDetail/index.tsx
Labels: 🐛 bug

#247 [CRAB-102] throwOnError추가 및 footer 정보 수정
  src/app/academy/(workspace)/[id]/dashboard/components/(principal)/ChallengeEditForm/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/(student)/ChallengeFeed/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/(student)/MyChallenge/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/AllChallengeContents/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/StudentCardList/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/StudentChallengeContents/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/create/components/Third.tsx
  src/app/academy/(workspace)/[id]/feed/components/CommentList/index.tsx
  src/app/academy/(workspace)/[id]/market/components/ChallengeCardList/index.tsx
  src/app/academy/(workspace)/[id]/market/components/Release/First.tsx
  src/app/academy/(workspace)/[id]/public-challenge/components/PublicCardList/index.tsx
  src/app/academy/(workspace)/[id]/setting/components/InstructorList/index.tsx
  src/app/academy/(workspace)/[id]/setting/components/StudentList/index.tsx
  src/app/my/components/academy-list/index.tsx
  src/features/academy/(workspace)/components/my-challenge-list/index.tsx
  src/shared/components/Footer/index.tsx
  src/shared/hooks/academy/useGetInfiniteAcademyInstructorList.ts
  src/shared/hooks/academy/useGetInfiniteAcademyList.ts
  src/shared/hooks/academy/useGetInfiniteAcademyMemberDetailList.ts
  src/shared/hooks/academy/useGetInfiniteAcademyStudentList.ts
  src/shared/hooks/challenge/useGetInfiniteFeedChallengeContents.ts
  src/shared/hooks/challenge/useGetInfiniteStudentChallengeContents.ts
  src/shared/hooks/challenge/useGetInfiniteStudentChallengeList.ts
  src/shared/hooks/challenge/useGetInfiniteStudentChallengeProgressList.ts
  src/shared/hooks/challenge/useGetInfiniteTeacherChallengeList.ts
  src/shared/hooks/challenge/useInfiniteMyChallengeContents.ts
  src/shared/hooks/comments/useGetInfiniteComments.ts
  src/shared/hooks/market/useGetInfiniteMarketChallenges.ts
  src/shared/hooks/public/useGetInfinitePublicChallenge.ts
Labels: ✨ feature

#251 [CRAB-103] 기관 초대코드 입력 후 경로 변경
  src/features/main/components/UserMenu/index.tsx
  src/shared/hooks/invitation/useEnrollInvitation.ts
Labels: 🐛 bug

#254 [CRAB-104] 챌린지 생성 요금제 수정
  src/app/my/components/invitation-modal/index.tsx
  src/app/space/enroll/page.tsx
  src/features/space/enroll/components/form.tsx
  src/shared/enums/academy.ts
  src/shared/hooks/invitation/useEnrollInvitation.ts
Labels: ✨ feature

#255 [Deploy] 2024년 12월 7일 Daily Deploy
  src/app/my/components/invitation-modal/index.tsx
  src/app/space/enroll/page.tsx
  src/features/space/enroll/components/form.tsx
  src/shared/enums/academy.ts
  src/shared/hooks/invitation/useEnrollInvitation.ts
Labels: 🍠 deploy

#257 [CRAB-105] 초대코드 실패시 클릭 오류
  src/app/my/components/invitation-modal/index.tsx
Labels: ✨ feature

#259 [CRAB-106] 개인정보 처리 방침 등록, s3 image-url 환경변수 변경
  next.config.mjs
  src/app/academy/(workspace)/[id]/dashboard/components/ChallengeDetail/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/Toggle/index.tsx
  src/app/academy/(workspace)/[id]/market/components/ChallengeContent/index.tsx
  src/features/main/components/TermModal/index.tsx
Labels: ✨ feature

#262 [CRAB-107] 1차 출시 이전 QA 반영
  package.json
  src/app/academy/(workspace)/[id]/dashboard/components/(student)/CreateChallengeForm/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/AnimateCard/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/ChallengeDetail/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/MyChallengeContentForm/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/create/components/First.tsx
  src/app/academy/(workspace)/[id]/dashboard/create/components/Second.tsx
  src/app/academy/(workspace)/[id]/market/components/ChallengeContent/index.tsx
  src/app/academy/(workspace)/[id]/market/components/ModalContent/index.tsx
  src/app/academy/(workspace)/[id]/setting/components/InstitutionProfileForm/index.tsx
  src/app/academy/(workspace)/[id]/setting/management/institution/components/EditForm/index.tsx
  src/app/academy/(workspace)/[id]/setting/management/invitation/components/Invitation/index.tsx
  src/app/api/academy/member/count/route.ts
  src/app/api/image/upload/route.ts
  src/app/profile/components/ProfileEditForm/index.tsx
  src/shared/apis/academy.ts
  src/shared/constants/query-keys.ts
  src/shared/hooks/academy/useGetAcademyMember.ts
  src/shared/hooks/images/use-get-presigned-url.ts
  src/shared/types/acadmy.ts
  src/shared/types/image.ts
  yarn.lock
Labels: ✨ feature

#265 [CRAB-108] 1차 QA 반영사항 수정
  src/app/academy/(workspace)/[id]/dashboard/components/StudentChallengeContents/index.tsx
  src/app/academy/(workspace)/[id]/market/page.tsx
  src/app/my/components/invitation-modal/index.tsx
Labels: ✨ feature

#270 [CRAB-109] 1차 QA 반영사항 수정
  src/app/academy/(workspace)/[id]/dashboard/components/(principal)/DashBoardUI/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/AllChallengeContents/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/Menubar/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/page.tsx
  src/app/api/challenge/list/route.ts
  src/app/my/components/academy-list/index.tsx
  src/shared/apis/academy.ts
  src/shared/apis/challenge.ts
  src/shared/hooks/challenge/useGetInfiniteMyAcademyChallenge.ts
  src/shared/hooks/challenge/useGetInfiniteTeacherChallengeList.ts
  src/shared/types/acadmy.ts
Labels: ✨ feature

#269 [CRAB-110] 1차 QA 반영사항 수정
  public/images/animation/alert.gif
  public/images/animation/loading.gif
  public/images/animation/no_content.gif
  public/images/icons/icon_cry.webp
  src/app/academy/(workspace)/[id]/dashboard/components/AllChallengeContents/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/ChallengeDetail/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/StudentChallengeContents/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/create/components/Second.tsx
  src/app/academy/(workspace)/[id]/dashboard/create/components/Third.tsx
  src/app/academy/(workspace)/[id]/dashboard/create/page.tsx
  src/app/academy/(workspace)/[id]/feed/components/ChallengeDetail/index.tsx
  src/app/academy/(workspace)/[id]/market/components/ChallengeCardList/index.tsx
  src/app/academy/(workspace)/[id]/market/components/ChallengeDetail/index.tsx
  src/app/academy/(workspace)/[id]/market/components/ModalDetail/index.tsx
  src/app/academy/(workspace)/[id]/public-challenge/components/PublicCardList/index.tsx
  src/app/academy/(workspace)/[id]/setting/components/InstitutionProfileForm/index.tsx
  src/app/academy/(workspace)/[id]/setting/components/InstructorList/index.tsx
  src/app/academy/(workspace)/[id]/setting/components/StudentList/index.tsx
  src/features/academy/(workspace)/hooks/use-image.ts
  src/shared/components/FallbackMessage/index.tsx
  src/shared/utils/schema.ts
Labels: ✨ feature

#276 [CRAB-112] 마이페이지 수정
  src/app/academy/(workspace)/[id]/dashboard/components/AllChallengeContents/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/create/components/Third.tsx
  src/app/academy/(workspace)/[id]/market/components/ChallengeContent/index.tsx
  src/app/academy/(workspace)/[id]/market/components/ModalContent/index.tsx
  src/app/academy/(workspace)/[id]/setting/layout.tsx
  src/app/academy/(workspace)/[id]/setting/management/institution/components/InstitutionEdit/index.tsx
  src/app/academy/(workspace)/[id]/setting/management/student/components/MemberDetail/index.tsx
  src/app/profile/components/EmailForm/index.tsx
  src/app/profile/components/PasswordForm/index.tsx
  src/app/profile/components/ProfileEdit/index.tsx
  src/app/profile/components/ProfileEditForm/index.tsx
  src/app/profile/components/Sidebar/index.tsx
  src/app/profile/layout.tsx
  src/app/profile/page.tsx
  src/app/profile/password/page.tsx
  src/features/academy/(workspace)/utils/challengeState.ts
  src/shared/apis/challenge.ts
  src/shared/constants/tab-menu.ts
  src/shared/hooks/challenge/useGetInfiniteMyAcademyChallenge.ts
  src/shared/hooks/market/useReleaseChallenge.ts
  src/shared/utils/schema.ts
Labels: ✨ feature

#279 [CRAB-113] 챌린지 전체보기 카테고리 추가
  src/app/academy/(workspace)/[id]/dashboard/components/(principal)/DashBoardUI/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/AllChallengeContents/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/ChallengeDetail/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/Menubar/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/page.tsx
  src/app/api/challenge/list/route.ts
  src/app/my/components/academy-list/index.tsx
  src/shared/apis/academy.ts
  src/shared/hooks/challenge/useGetInfiniteMyAcademyChallenge.ts
  src/shared/types/acadmy.ts
Labels: ✨ feature

#280 [CRAB-114] 챌린지 인증글 반려 추가
  src/app/academy/(workspace)/[id]/dashboard/components/StudentCard/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/StudentCardList/index.tsx
  src/shared/hooks/challenge/useApprovalChallenge.ts
Labels: ✨ feature

#286 [CRAB-115] 챌린지 수정 관련 변경사항 적용
  src/app/academy/(workspace)/[id]/dashboard/[challengeId]/page.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/AllChallengeContents/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/ChallengeDetail/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/Menubar/index.tsx
  src/app/academy/(workspace)/[id]/market/components/ChallengeCardList/index.tsx
  src/app/academy/(workspace)/[id]/market/page.tsx
  src/app/academy/(workspace)/[id]/setting/management/invitation/components/Invitation/index.tsx
  src/features/main/components/AcademyProfileMenu/index.tsx
  src/shared/apis/challenge.ts
  src/shared/constants/tab-menu.ts
  src/shared/types/acadmy.ts
Labels: ✨ feature

#287 [Deploy] 2024년 12월 10일 Daily Deploy
  src/app/academy/(workspace)/[id]/dashboard/[challengeId]/page.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/AllChallengeContents/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/ChallengeDetail/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/Menubar/index.tsx
  src/app/academy/(workspace)/[id]/market/components/ChallengeCardList/index.tsx
  src/app/academy/(workspace)/[id]/market/page.tsx
  src/app/academy/(workspace)/[id]/setting/management/invitation/components/Invitation/index.tsx
  src/features/main/components/AcademyProfileMenu/index.tsx
  src/shared/apis/challenge.ts
  src/shared/constants/tab-menu.ts
  src/shared/types/acadmy.ts
Labels: 🍠 deploy

#289 [CRAB-117] 학생 인증글 관련 에러 수정
  src/app/academy/(workspace)/[id]/dashboard/[challengeId]/page.tsx
Labels: 🐛 bug

#290 [Deploy] 2024년 12월 10일 Daily Deploy
  src/app/academy/(workspace)/[id]/dashboard/[challengeId]/page.tsx
Labels: 🍠 deploy

#293 [CRAB-119] 챌린지 마켓 레이아웃 오류 수정 및 모달 수정
  src/app/academy/(workspace)/[id]/dashboard/components/AnimateCard/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/ChallengeDetail/index.tsx
  src/app/academy/(workspace)/[id]/market/components/ChallengeContent/index.tsx
  src/app/academy/(workspace)/[id]/market/components/ModalContent/index.tsx
  src/app/academy/(workspace)/[id]/market/page.tsx
  src/app/academy/(workspace)/[id]/public-challenge/components/PublicDetail/index.tsx
  src/app/academy/(workspace)/[id]/public-challenge/components/PublicModal/index.tsx
Labels: ✨ feature

#298 [CRAB-121] Pricing 페이지 추가
  public/images/card.webp
  src/app/academy/(workspace)/[id]/dashboard/[challengeId]/page.tsx
  src/app/academy/(workspace)/[id]/dashboard/page.tsx
  src/app/pricing/page.tsx
  src/features/main/components/FifthBanner/index.tsx
  src/features/main/components/FourthBanner/index.tsx
  src/features/main/components/UserMenu/index.tsx
Labels: ✨ feature

#300 [CRAB-123] 학원 로그인 뷰 수정
  src/features/main/components/LoginModal/index.tsx
  src/features/main/components/UserMenu/index.tsx
Labels: ✨ feature

#301 [CRAB-122] 수정 권한 변경
  src/app/academy/(workspace)/[id]/dashboard/components/(principal)/ChallengeCoreEditForm/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/(principal)/ChallengeEditForm/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/ChallengeDetail/index.tsx
  src/app/api/challenge/route.ts
  src/shared/apis/challenge.ts
  src/shared/types/acadmy.ts
  src/shared/utils/schema.ts
Labels: ✨ feature

#304 [CRAB-124] 챌린지 요금제 내용 추가
  src/app/pricing/page.tsx
  src/features/pricing/component/PricingBox/index.tsx
  src/shared/components/FramerScale/index.tsx
  src/shared/constants/pricing.ts
Labels: ✨ feature

#305 [Deploy] 2024년 12월 12일 Daily Deploy
  src/app/pricing/page.tsx
  src/features/pricing/component/PricingBox/index.tsx
  src/shared/components/FramerScale/index.tsx
  src/shared/constants/pricing.ts
Labels: 🍠 deploy

#307 [CRAB-125] 크래빗 챌린지 & 크래빗 장학카드 페이지
  public/images/logo/logo_abc.webp
  public/images/logo/logo_accomplishment.webp
  public/images/logo/logo_book.webp
  public/images/logo/logo_card.webp
  public/images/logo/logo_challenge.webp
  public/images/logo/logo_clock.webp
  public/images/logo/logo_idea.webp
  public/images/logo/logo_money.webp
  public/images/logo/logo_school.webp
  public/images/logo/logo_write.webp
  src/app/card/page.tsx
  src/app/challenge/page.tsx
  src/app/pricing/page.tsx
  src/features/card/components/CardInfoBox/index.tsx
  src/features/challenge/components/ChallengeBox/index.tsx
  src/features/main/components/UserMenu/index.tsx
  src/shared/constants/card.ts
  src/shared/constants/challenge.ts
  src/shared/constants/main-cards.ts
  tailwind.config.ts
Labels: ✨ feature

#308 [Deploy] 2024년 12월 13일 Daily Deploy
  public/images/logo/logo_abc.webp
  public/images/logo/logo_accomplishment.webp
  public/images/logo/logo_book.webp
  public/images/logo/logo_card.webp
  public/images/logo/logo_challenge.webp
  public/images/logo/logo_clock.webp
  public/images/logo/logo_idea.webp
  public/images/logo/logo_money.webp
  public/images/logo/logo_school.webp
  public/images/logo/logo_write.webp
  src/app/card/page.tsx
  src/app/challenge/page.tsx
  src/app/pricing/page.tsx
  src/features/card/components/CardInfoBox/index.tsx
  src/features/challenge/components/ChallengeBox/index.tsx
  src/features/main/components/UserMenu/index.tsx
  src/shared/constants/card.ts
  src/shared/constants/challenge.ts
  src/shared/constants/main-cards.ts
  tailwind.config.ts
Labels: 🍠 deploy

#310 [CRAB-126] 장학카드 신청하기
  src/app/academy/(workspace)/[id]/dashboard/create/components/Third.tsx
  src/app/card/page.tsx
  src/app/space/enroll/page.tsx
  src/features/card/components/CardApply/index.tsx
  src/features/card/components/CardInfo/index.tsx
  src/features/main/components/LoginModal/index.tsx
  src/shared/components/SmallModal/index.tsx
  src/shared/constants/card.ts
Labels: ✨ feature

#311 [Deploy] 2024년 12월 16일 Daily Deploy
  src/app/academy/(workspace)/[id]/dashboard/create/components/Third.tsx
  src/app/card/page.tsx
  src/app/space/enroll/page.tsx
  src/features/card/components/CardApply/index.tsx
  src/features/card/components/CardInfo/index.tsx
  src/features/main/components/LoginModal/index.tsx
  src/shared/components/SmallModal/index.tsx
  src/shared/constants/card.ts
Labels: 🍠 deploy

#313 [CRAB-127] 장학카드 자주묻는 질문
  public/images/card_info.webp
  src/app/academy/(workspace)/[id]/dashboard/components/Toggle/index.tsx
  src/app/card/page.tsx
  src/features/card/components/CardApply/index.tsx
  src/features/card/components/CardInfo/index.tsx
  src/features/card/components/CardInfoBox/index.tsx
  src/features/card/components/CardQuestion/index.tsx
  src/features/card/components/CardStandard/index.tsx
  src/features/card/hooks/useSectionRef/useSectionRef.tsx
  src/shared/constants/question.ts
Labels: ✨ feature

#314 [Deploy] 2024년 12월 18일 Daily Deploy
  public/images/card_info.webp
  src/app/academy/(workspace)/[id]/dashboard/components/Toggle/index.tsx
  src/app/card/page.tsx
  src/features/card/components/CardApply/index.tsx
  src/features/card/components/CardInfo/index.tsx
  src/features/card/components/CardInfoBox/index.tsx
  src/features/card/components/CardQuestion/index.tsx
  src/features/card/components/CardStandard/index.tsx
  src/features/card/hooks/useSectionRef/useSectionRef.tsx
  src/shared/constants/question.ts
Labels: 🍠 deploy

#316 [CRAB-128] textaure로 작성된 부분 줄바꿈 처리
  src/app/academy/(workspace)/[id]/dashboard/components/(student)/MyChallengeDetail/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/ChallengeDetail/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/StudentChallengeContent/index.tsx
  src/app/academy/(workspace)/[id]/feed/components/ChallengeDetail/index.tsx
  src/app/academy/(workspace)/[id]/feed/components/Comment/index.tsx
  src/app/academy/(workspace)/[id]/feed/components/CommentList/index.tsx
  src/app/academy/(workspace)/[id]/market/components/ChallengeContent/index.tsx
  src/app/academy/(workspace)/[id]/market/components/ModalContent/index.tsx
  src/app/academy/(workspace)/[id]/public-challenge/components/PublicDetail/index.tsx
  src/app/academy/(workspace)/[id]/public-challenge/components/PublicModal/index.tsx
  src/app/academy/(workspace)/[id]/setting/management/instructor/components/InstructorDetail/index.tsx
  src/app/academy/(workspace)/[id]/setting/management/student/components/MemberDetail/index.tsx
  src/shared/components/ProfileCard/index.tsx
Labels: ✨ feature

#320 [CRAB-129] 학생 인증화면 글씨크기 수정 및 DAY 연결
  src/app/academy/(workspace)/[id]/dashboard/components/(student)/ChallengeStatusBar/ChallengeStatusBar.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/(student)/CreateChallengeForm/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/(student)/MyChallengeDetail/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/Toggle/index.tsx
  src/features/academy/(workspace)/components/state-label/index.tsx
  src/features/academy/(workspace)/utils/challengeState.ts
  src/shared/components/Textarea/index.tsx
  src/shared/utils/calculateChallengeDay.ts
Labels: ✨ feature

#321 [Deploy] 2024년 12월 27일 Daily Deploy
  src/app/academy/(workspace)/[id]/dashboard/components/(student)/ChallengeStatusBar/ChallengeStatusBar.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/(student)/CreateChallengeForm/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/(student)/MyChallengeDetail/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/Toggle/index.tsx
  src/features/academy/(workspace)/components/state-label/index.tsx
  src/features/academy/(workspace)/utils/challengeState.ts
  src/shared/components/Textarea/index.tsx
  src/shared/utils/calculateChallengeDay.ts
Labels: 🍠 deploy

#323 [CRAB-130] 인증바 모바일 수정
  src/app/academy/(workspace)/[id]/dashboard/components/(student)/ChallengeStatusBar/ChallengeStatusBar.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/(student)/CreateChallengeForm/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/Toggle/index.tsx
Labels: ✨ feature

#324 [Deploy] 2024년 12월 27일 Daily Deploy
  src/app/academy/(workspace)/[id]/dashboard/components/(student)/ChallengeStatusBar/ChallengeStatusBar.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/(student)/CreateChallengeForm/index.tsx
  src/app/academy/(workspace)/[id]/dashboard/components/Toggle/index.tsx
Labels: ✨ feature
